### ISSUE TITLE
GPU加速语音生成字幕

### ISSUE THREAD

**Issue by shawn8888** [Makememo/MemoAI#10]
找了一圈，似乎没有找到GPU加速啊！
我用的是Windows版，GPU: 	NVIDIA GeForce GTX 950
![image](https://github.com/Makememo/MemoAI/assets/8271101/e28f5e53-fcd0-4886-8df2-97642237bd0e)

**Comment by Makememo** [comment]
已经更新，请前往：https://memo.ac/releases.html 下载，用的愉快～
