### ISSUE TITLE
字幕排列问题

### ISSUE THREAD

**Issue by ehowang** [Makememo/MemoAI#103]
![photo_2023-11-30 21 12 15](https://github.com/Makememo/MemoAI/assets/57342585/14f963ba-eb48-476a-973a-e600852a07d1)
当翻译短视频时，由于无法编辑字幕让字幕换行或者竖向排列，会导致字幕超出屏幕界限，进而导致字幕丢失

**Comment by Makememo** [comment]
后续我们会重点优化剪辑这一块，会给一个好的产品体验。

**Comment by Makememo** [comment]
The new version is supported.
