### ISSUE TITLE
批量转写中的问题

### ISSUE THREAD

**Issue by zgbjmy2009** [Makememo/MemoAI#106]
在批量转写中：
1、无法在批量中定义导出的字幕是原语言、目标语言还是双语。经过实践默认是原语言的。双语或者目标语言还得手动解决。

2、在转写过程中经常出现翻译错误的问题（我这里使用的是微软翻译），不知道是网速的原因还是限制问题或者是什么。

3、两转写过程中经常显示已经完成操作，但是导出那里还是黑色的。按理说完成导出操作才算完成过程后面的绿色勾才会显示。而且UI与实际程序进程有差距，很多时候UI显示完成，但是显卡仍然在拼命工作，实际工作没有完成。这在导出内嵌字幕的视频时也会发生。

4、视频如果是转录导出视频，原视频格式2K最后导出发现是720P的。

5、程序运行，在C盘（C:\Users\Name\AppData\Roaming\Memo\temp）是否也产生大量缓存？

6、纯英文的模型比如：ggml-large-32-2.en用不了，目前用多语言的模型才可以。
![2023-12-01 234929](https://github.com/Makememo/MemoAI/assets/18496124/65304e2a-bc64-4dd1-b6cb-1a78f4c794b7)

**Comment by zgbjmy2009** [comment]
另外在早晨批量转换过程中总有错误： Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed

**Comment by Makememo** [comment]
Error sending from webFrameMain: Error: Render frame was disposed before WebFrameMain could be accessed 问题我们跟踪一下。
 
 其他的问题我们后续逐个处理。感谢反馈。

**Comment by zgbjmy2009** [comment]
晚上使用软件，在本地批量的时候又遇到如下错误（没办法只好自己找到LOG日志了）：
[info 21:03:40.978 (error)]  ----------------------------- application starting [2023-12-02-09-03-40] ---------------------------------------
[info 21:03:51.171        ]  TypeError: Cannot read properties of undefined (reading 'abort')
    at J2r (evalmachine.<anonymous>:1:1623153)
    at evalmachine.<anonymous>:1:1838104
    at new Promise (<anonymous>)
    at Wre (evalmachine.<anonymous>:1:1838084)
    at EventTarget.<anonymous> (evalmachine.<anonymous>:1:5251056)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:731:20)
    at EventTarget.dispatchEvent (node:internal/event_target:673:26)
    at abortSignal (node:internal/abort_controller:308:10)
    at AbortController.abort (node:internal/abort_controller:338:5)
    at evalmachine.<anonymous>:1:5251547
[info 21:03:51.171        ]  transcript abort false
[error 21:03:51.173        ]  (node:16956) UnhandledPromiseRejectionWarning: false
(Use `Memo --trace-warnings ...` to show where the warning was created)
[error 21:03:51.173        ]  (node:16956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[error 21:04:01.632        ]  Error: Error: net::ERR_CONNECTION_RESET
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49462)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
[info 21:04:01.632        ]  check-update error
[info 21:05:09.586        ]  task abort
[info 21:05:09.587        ]  TypeError: Cannot read properties of undefined (reading 'abort')

**Comment by zgbjmy2009** [comment]
在中途使用的时候发现：

1、 TTS配音（使用视频长度的时候）下载后自动裁剪了空白的段落，导致TTS和视频不能同步！
2、TTS配音（使用音频长度的时候）下载后比原视频时长要长，导致TTS和视频也不能同步！
3、测试的时候批量操作挺好用，买了个会员感觉新版本更加不稳定了！！！

**Comment by Makememo** [comment]
1. 额外的文件夹有提供片段供使用，如果希望是完整合成导出，需要等后续版本解决
2. 这块坦白说没有好的解决方案，两种语言的文本长度，速度，要么加快音频，要么放慢视频，在问题一中来解决。
3. 批量目前还不是很稳定，我们接下来会重点优化，使用批量时：
- 如果有报错，务必保证音频保证有声音，不然无法转写。
- 已知问题：如果转写过程中频繁暂停操作，会打断任务，造成缓存，请额外新建一个空间解决，

针对无法转写的音频，请使用 zip 发送给 team@memo.ac，需要额外测试一下视频问题，视频格式文本很多，一一兼容需要样本和时间。

**Comment by Makememo** [comment]
微软翻译不支持长文本，下个版本会优化。
