### ISSUE TITLE
whisper v3 新增了廣東話，但在Memo沒有廣東話選擇

### ISSUE THREAD

**Issue by WingCH** [Makememo/MemoAI#107]
**Describe the bug**
Video: https://www.youtube.com/watch?v=q7_4-oJOzUo

選擇繁體中文效果不好，但選擇 `自動檢測` 效果就很好，應該是whisper自動檢測到是廣東話，如果可以手動選擇就更好

**To Reproduce**
1. Go to '主頁'
2. Click on '選擇本地媒體' -> 選擇模型
3. 源文件語言 沒有廣東話

**Screenshots**
![62961](https://github.com/Makememo/MemoAI/assets/19588517/8ab00280-939a-4df9-84d0-ed5362748630)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version v1.1.1

**Additional context**

**Comment by Makememo** [comment]
V3 质量不是很好，带来很多问题，我们考虑隐藏。
