### ISSUE TITLE
New Cantonese support on v1.1.2 Beta issue

### ISSUE THREAD

**Issue by sdugoten** [Makememo/MemoAI#112]
**Describe the bug**
The new version now correctly translate the Cantonese using the "Cantonese" in Language.  However, the transcript will display in one single line

**To Reproduce**
<img width="474" alt="2" src="https://github.com/Makememo/MemoAI/assets/7108552/00071530-b7e1-42a6-a444-bed964d05dcf">

**Expected behavior**
It should be line by line instead of having all thing in one single sentence

**Screenshots**
<img width="490" alt="Screen-Shot-2023-12-06-13-20-34" src="https://github.com/Makememo/MemoAI/assets/7108552/f80e49da-075f-47f6-b07d-45dc7351d460">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Mac
 - Version [e.g. 22] v1.1.2 Beta 

**Additional context**
Also tried Auto setting with the following prompt "以下係香港嘅港式廣東話", that will show better result with correct line spacing.  However, for whatever reason some sentence correctly transcribe into Cantonese while another line is not.  Just not consistent.  You can see some sentence using "係" while some other use "是"

<img width="478" alt="3" src="https://github.com/Makememo/MemoAI/assets/7108552/95c86446-4114-4ffd-80bc-88b07d2122a0">
<img width="578" alt="4" src="https://github.com/Makememo/MemoAI/assets/7108552/dfbba335-6635-4152-add9-7d699ba152f2">

You can get the sample video here  https://drive.google.com/file/d/1RwWGfE8mEq_6TxFJD72vHEuQYidKzAz1/view?usp=sharingå

**Comment by Makememo** [comment]
![2023-12-06214726@2x](https://github.com/Makememo/MemoAI/assets/140973261/eca3aa65-0274-4e5d-9ef1-1379d343e561)

The next version is fixed.

**Comment by sdugoten** [comment]
O

> ![2023-12-06214726@2x](https://private-user-images.githubusercontent.com/140973261/288426684-eca3aa65-0274-4e5d-9ef1-1379d343e561.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NzA5MTEsIm5iZiI6MTcwMTg3MDYxMSwicGF0aCI6Ii8xNDA5NzMyNjEvMjg4NDI2Njg0LWVjYTNhYTY1LTAyNzQtNGU1ZC05ZWYxLTEzNzlkMzQzZTU2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwNlQxMzUwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjZkNjY5MDA5MDBmZmQ0ZDhjM2ZjZWY2ZWZlY2FmMzJkMzQ0OWVhNmE1NWVhMTZhNzE3NTllMzZmNzk0ODQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sstD1rFFZfNd_4WEJA-eH80JS0gShfAzXsiEXKHHr0s)
> 
> The next version is fixed.

I wonder where do I get the next version to test? thanks.

**Comment by sdugoten** [comment]
> https://github.com/Makememo/MemoAI/releases v1.1.3 this week will releases.

Mac works with v1.1.3.  However, if you choose Cantonese on Windows version, it will crash the transcript engine and just not doing anything.

**Comment by sdugoten** [comment]
Moreover, it seems the Cantonese will break when the video is long.  You can try this one. (I did the test on Mac v1.1.3)

1.  It will make some extremely long sentence at the end of transcript (if the video is long enough.  Usually happen a lot for video over 20 mins)

2. It will forget "Cantonese" and it will start doing Traditional Chinese again 

You can see screenshot regarding point 1 and point 2 below

https://drive.google.com/file/d/10h3prlXRT3Hyc5SkvL6cz3a2tau7m38G/view?usp=sharing

<img width="483" alt="image" src="https://github.com/Makememo/MemoAI/assets/7108552/47ce735a-5497-4636-bb37-071bdeb02d64">

**Comment by Makememo** [comment]
I checked this video, Chinese and English mixed, this recognition is a model problem, it is a pity that we can not optimize it at present.

**Comment by Makememo** [comment]
> > https://github.com/Makememo/MemoAI/releases v1.1.3 this week will releases.
> 
> Mac works with v1.1.3. However, if you choose Cantonese on Windows version, it will crash the transcript engine and just not doing anything.

Windows does not have support.

**Comment by sdugoten** [comment]
> > > https://github.com/Makememo/MemoAI/releases v1.1.3 this week will releases.
> > 
> > 
> > Mac works with v1.1.3. However, if you choose Cantonese on Windows version, it will crash the transcript engine and just not doing anything.
> 
> Windows does not have support.

What about the long sentence issue?  I saw another thread also mention about the long sentence issue.  I know there is a switch that you can force the length of the transcribed sentence, but the position to cut the sentence is pretty weird in Chinese...

**Comment by sdugoten** [comment]
> I checked this video, Chinese and English mixed, this recognition is a model problem, it is a pity that we can not optimize it at present.

I wonder if we can specify when to start the transcribe?  If we are allowed to choose where to start and where to end, at least I can do the transcribe part by part so that I can avoid mixing Chinese and English together.

**Comment by Makememo** [comment]
It will be supported later.
