### ISSUE TITLE
浏览器插件的形式，实时转译加字幕

### ISSUE THREAD

**Issue by nameRoy** [Makememo/MemoAI#116]
虽然目前支持了粘贴 URL 然后下载到本地的形式，但这无疑增加了下载的时间，如果可以增加浏览器插件的形式，这样使用起来个人觉得会更舒服。

**Comment by Makememo** [comment]
It costs money to use cloud services directly.

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/releases/tag/v1.3.9
