### ISSUE TITLE
语音识别转写出来的句子过长

### ISSUE THREAD

**Issue by wuyafei** [Makememo/MemoAI#118]
**Describe the bug**
设置了最大转写长度
<img width="459" alt="bug0" src="https://github.com/Makememo/MemoAI/assets/5711329/db01a199-e8b8-4172-b4d9-381b32288062">

但是转出来的句子还是有非常长的
<img width="978" alt="bug1" src="https://github.com/Makememo/MemoAI/assets/5711329/f9a4ec4e-e3d7-4cb8-930e-a19f0b2c332c">

设置了最大转写长度后断句就没有那么准了
<img width="466" alt="bug3" src="https://github.com/Makememo/MemoAI/assets/5711329/032d7a91-4934-4ffa-a7df-5fa22bb75d74">

希望能优化

另外再提几个使用过程中遇到的小bug
1. 批量工具选了要翻译也不会自动进行，都需要手动去处理
2. 导出视频风扇狂转，导出完成后还一直在转，查看进程是ffmpeg还在运行，强制杀了才停止
3. 批量工具偶尔会自动卡在某一步，必须重新点一下开始才会进行下去

最后感谢作者创造了非常好用的工具

**Desktop (please complete the following information):**
 - OS: [macOS 14]
 - Model[Medium.en]
 - Version [1.1.3]

**Comment by Makememo** [comment]
https://memo.ac/zh/blog/How-to-use-AI-to-translate-subtitles 查阅此教程，按照教程添加一下提示词。

**Comment by wuyafei** [comment]
> https://memo.ac/zh/blog/How-to-use-AI-to-translate-subtitles 查阅此教程，按照教程添加一下提示词。

增加之后确实有好转，有点神奇，不过还是有较长的语句，请问提示词使用有什么讲究，我只是加了,.这也的提示词
<img width="1002" alt="bu4" src="https://github.com/Makememo/MemoAI/assets/5711329/de248085-147b-493d-bb7b-9b47319d7a25">
