### ISSUE TITLE
粵語影片，選擇粵語 Large(v3) 會產生英文字幕

### ISSUE THREAD

**Issue by WingCH** [Makememo/MemoAI#119]
**Describe the bug**

https://www.youtube.com/watch?v=q7_4-oJOzUo

選擇 `粵語`, 會出現英文字幕，神奇的是，英文是翻譯正確的

<img width="1236" alt="image" src="https://github.com/Makememo/MemoAI/assets/19588517/94992b28-6481-4c04-8c3d-4cbfb24bdbc3">

但選擇 `自動檢測`，會出現粵語繁體中文字幕，這是正確的
<img width="1236" alt="image" src="https://github.com/Makememo/MemoAI/assets/19588517/86c25c21-b8fa-43e8-bffc-85251a9971fd">

**Desktop (please complete the following information):**
 - OS 13.6.1（22G313）
 - Model Large(v3)
 - Version v1.1.3

**Additional context**

**Comment by Makememo** [comment]
![2023-12-11214251@2x](https://github.com/Makememo/MemoAI/assets/140973261/38575cb6-ef51-4b98-9617-662588c3afc3)
测试正常🤔

**Comment by WingCH** [comment]
我開啟了 `轉寫檢測語音活動` 和 `CoreML`
會有影響嗎？

**Comment by WingCH** [comment]
嘗試過關閉轉寫檢測語音活動 和 CoreML 效果一樣

**Comment by WingCH** [comment]
重新下載Large(v3)後 好像正常了 😂
