### ISSUE TITLE
使用智谱 AI 翻译，中文字幕和英文字幕对不上

### ISSUE THREAD

**Issue by MarcoGWR** [Makememo/MemoAI#121]
总是出现，前面几句的字数特别多，但是后面就完全空了的状态
![WX20231213-171132@2x](https://github.com/Makememo/MemoAI/assets/153720531/d8f15420-c1c6-47e7-9d6c-9ba22e0ddc2b)

**Comment by Makememo** [comment]
https://memo.ac/zh/blog/How-to-use-AI-to-translate-subtitles
