### ISSUE TITLE
[Suggestion] Website UI Logo display in dark night mode

### ISSUE THREAD

**Issue by rubickecho** [Makememo/MemoAI#127]
**Describe the bug**
Memo is  so good ai application
In website is in dark mode, the logo show black.

**Expected behavior**
Suggested white display

**Screenshots**
![image](https://github.com/Makememo/MemoAI/assets/14804014/9c7d782c-60e3-4cf4-bafe-887cd1083ba4)

**Comment by Makememo** [comment]
Thanks
