### ISSUE TITLE
Untranslated UI elements

### ISSUE THREAD

**Issue by candideu** [Makememo/MemoAI#13]
# **Describe the bug**
This is a fantatsic app with a lot of potential! That said, despite selecting "English", a number of UI elements are not translated yet.

# **Screenshots**
## Welcome
![image](https://github.com/Makememo/MemoAI/assets/55474996/2bb9fe0d-78e8-4774-8a16-20cc307c364a)

Additionally, when I clicked "Done" using [one of the invitation codes listed here](https://github.com/openai/whisper/discussions/1028#discussioncomment-6890841) (` mape-7ssz-Xj2A-P5Wf`), an error popped up at the top of the app which also wasn't translated.

## Transcription page
![image](https://github.com/Makememo/MemoAI/assets/55474996/0da4759b-9023-4436-9630-f543b867e072)

## Export Window
![image](https://github.com/Makememo/MemoAI/assets/55474996/64cd562f-eea0-4c3a-9eca-963905f6bf86)

## Hover Text
![Memo_Hover](https://github.com/Makememo/MemoAI/assets/55474996/03c4b5c9-dbcc-4227-ab6f-d04ed9e37909)

## Pencil Icon Window
![image](https://github.com/Makememo/MemoAI/assets/55474996/b27ca654-5045-4b84-88ce-78a8a0ebbc66)

## Rectangle Icon Window
![image](https://github.com/Makememo/MemoAI/assets/55474996/0063e3f9-4666-41a6-a908-f4eae442f087)

## Dashboard Projects
![image](https://github.com/Makememo/MemoAI/assets/55474996/9cf2243e-49f4-4345-8236-e63fe68b5f86)

# **Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v1.0.5

# **Suggestions**
- Getting users to contribute translated strings

**Comment by Makememo** [comment]
Thank you so much for your feedback. We highly appreciate you taking the time to let us know about this issue. We will make fixing this a top priority for the next version update. Please let us know if you have any other suggestions - we aim to continuously improve our product based on feedback from valued customers like yourself.

**Comment by Makememo** [comment]
we fixed～

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/releases/tag/v1.0.6

**Comment by candideu** [comment]
Hi, thank you for fixing! Just wanted to flag a few untranslated elements that I've found in the latest version:

![image](https://github.com/Makememo/MemoAI/assets/55474996/b5f5ddf7-4139-4a18-9f29-96d34fd4016e)

![image](https://github.com/Makememo/MemoAI/assets/55474996/50dfa20a-e65f-449b-988b-b02f7d32edd1)
