### ISSUE TITLE
思维导图下载图片，字看不清楚

### ISSUE THREAD

**Issue by m1911star** [Makememo/MemoAI#133]
![mindmap](https://github.com/Makememo/MemoAI/assets/4948120/0414c8cd-a055-43d2-b1b0-62f3a33f6285)

**Comment by m1911star** [comment]
另外，当mindmap 比较大时，下载不全

**Comment by Makememo** [comment]
下個版本已經修復，近期會發出。

**Comment by Makememo** [comment]
已經修復 https://memo.ac/releases
