### ISSUE TITLE
Download stuck at 100% for Bilibili video

### ISSUE THREAD

**Issue by zhy3213** [Makememo/MemoAI#147]
**Describe the bug**
Download stuck at 100% for Bilibili video https://www.bilibili.com/video/BV13C4y1D7wK/

**To Reproduce**
1. On Memo tab, paste link `https://www.bilibili.com/video/BV13C4y1D7wK/` and click Transcribe.
2. Setting as 
<img width="483" alt="image" src="https://github.com/Makememo/MemoAI/assets/29100733/fa8f670f-d1cd-4065-bbb7-2a7b9e9d4867">

then click Transcribe.

3. The download process will start and stuck at 100%, transcribe process will not start

**Expected behavior**
transcribe process start after download is complete

**Screenshots**
<img width="1202" alt="image" src="https://github.com/Makememo/MemoAI/assets/29100733/9cc992b2-fe86-4224-b6e7-655127e884d4">

**Desktop (please complete the following information):**
 - OS: macOS 14.2.1
 - Model Medium
 - Version 1.1.5

**Comment by zhy3213** [comment]
And after this task stuck at 100% downloading, even after deleting this task in Memo tab, adding YouTube videos, which used to transcribe without issue, now fails to initiate the transcription process. Restarting the application seems to restore functionality for YouTube videos, but the problem persists with this particular Bilibili video.

**Comment by zhy3213** [comment]
Related logs:
```
[info 14:18:34.759        ]  [
  'https://www.bilibili.com/video/BV13C4y1D7wK/',
  '--prefer-free-formats',
  '--dump-json'
]
[info 14:18:49.143        ]  stop text to speech
[info 14:20:51.186        ]  all done
[info 14:20:51.187        ]  change file name /Users/zhanghaoyang/Library/Application Support/Memo/temp/external/external_e219e17c-6a36-493e-b0ff-8645bdf7ad6d.mkv /Users/zhanghaoyang/Library/Application Support/Memo/temp/external/【学院谈】消费主义已死？为什么品牌营销玩不转了？ [BV13C4y1D7wK].mkv
[info 14:20:51.187        ]  uncaughtException
[error 14:20:51.188 (error)]  Error: ENOENT: no such file or directory, rename '/Users/zhanghaoyang/Library/Application Support/Memo/temp/external/external_e219e17c-6a36-493e-b0ff-8645bdf7ad6d.mkv' -> '/Users/zhanghaoyang/Library/Application Support/Memo/temp/external/【学院谈】消费主义已死？为什么品牌营销玩不转了？ [BV13C4y1D7wK].mkv'
    at Object.renameSync (node:fs:1039:3)
    at srt (evalmachine.<anonymous>:1:1364561)
    at EventEmitter.<anonymous> (evalmachine.<anonymous>:1:5045519)
    at EventEmitter.emit (node:events:513:28)
    at ChildProcess.<anonymous> (evalmachine.<anonymous>:1:5041947)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:313:12)
[info 14:22:26.726        ]  stop text to speech
[info 14:23:05.706        ]  [
  'https://www.bilibili.com/video/BV13C4y1D7wK/',
  '--prefer-free-formats',
  '--dump-json'
]
[info 14:25:58.860        ]  stop text to speech
[info 14:31:53.908        ]  stop text to speech
[info 14:32:26.194        ]  [
  'https://www.youtube.com/watch?v=zmQmLoXHBHs',
  '--prefer-free-formats',
  '--dump-json'
]
[info 14:32:44.853        ]  stop text to speech
[info 14:34:29.897        ]  stop text to speech
[info 14:34:32.631        ]  stop text to speech
```

**Comment by Makememo** [comment]
It will be repaired later.

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/releases/tag/v1.1.6
