### ISSUE TITLE
whisper会出现识别错乱的补救方式

### ISSUE THREAD

**Issue by RekiDunois** [Makememo/MemoAI#148]
有时候whisper的推断会出现错乱的情况，表现形式是不停输出同一句话，我直接用whisper.cpp也会出现一样的问题。

<img width="568" alt="image" src="https://github.com/Makememo/MemoAI/assets/23435534/3b51a1fd-5438-49e3-ab53-aee840e8bdd6">

这属于whisper自己的问题，memo是否可以考虑，如果出现了这种情况，可以让用户选择出问题的那一段单独切下来去再次识别。因为这样的问题如果再次转写，是有概率避免的，而如果一个一两个小时的音频每次都要重新转写，也太麻烦了，所以希望能单独转写出问题的部分

**Comment by Makememo** [comment]
转写面版高级设置 - 语音检测打开会好点。

**Comment by Makememo** [comment]
![2023-12-30171956@2x](https://github.com/Makememo/MemoAI/assets/140973261/abe568c6-d1cf-41ac-8676-81bd38529a91)

**Comment by RekiDunois** [comment]
这个东西即使开了也会出现重复输出，只是频率降低了

**Comment by Makememo** [comment]
可以更换 large-v2 等模型，V3 确实会经常出现此类问题，社区也没有解决方案。
