### ISSUE TITLE
语言设置为中文情况下无法配置 OpenAI key，需要切换成英文才能配置。(v1.1.6)

### ISSUE THREAD

**Issue by zj1123581321** [Makememo/MemoAI#15]
**Describe the bug**
AI 总结的功能需要 OpenAI key，
但是语言设置为中文情况下无法配置 OpenAI key，需要切换成英文才能配置。

**To Reproduce**
- 语言设置为『中文』，设置里找不到 OpenAI key 配置地址
- 语言设置为『English』，可以在翻译设置里配置 OpenAI key

**Expected behavior**

**Screenshots**
![image](https://github.com/Makememo/MemoAI/assets/33171229/7ede94b0-fe66-4252-8a8d-a12e908177bc)

**Desktop (please complete the following information):**
 - OS: win11
 - Version 1.1.6

**Comment by Makememo** [comment]
是的，在 1.0.5 更新已经说过了这个问题。后续中文界面下会接入文心一言。
