### ISSUE TITLE
语音识别能力差

### ISSUE THREAD

**Issue by EricWong1994** [Makememo/MemoAI#153]
用的是英语识别准确率最高的模型， 但识别出来的结果很差，下图红色框中的文字都没识别出来。。。
且双语导出的字幕 时间戳与 英语的不同
<img width="1182" alt="image" src="https://github.com/Makememo/MemoAI/assets/48429995/ba235b05-4c03-4723-96f9-072de527adb8">

<img width="509" alt="image" src="https://github.com/Makememo/MemoAI/assets/48429995/3f54a558-8a69-4444-9538-0e0b33856371">

**Comment by Makememo** [comment]
能否发一下语音打包？

**Comment by EricWong1994** [comment]
[Uploading Compress.zip…]()

**Comment by EricWong1994** [comment]
[Compress.zip](https://github.com/Makememo/MemoAI/files/13830592/Compress.zip)

这个，刚才上传失败了

**Comment by Makememo** [comment]
测试了一下，是模型本身训练的问题，我们无法解决此问题，只能等待 Open AI 修复。另外需要和你解释一下大模型的运行原理。

- 大模型本身会经过多种数据训练，当时这个模型被训练材料应该有完整的片段，模型本身根据内容做了推理。
- 大模型会自动根据上文进行推理理解，不一定是直接识别。

如果是英文这里建议使用 small.en 可以获取更好的识别。
