### ISSUE TITLE
Could you guide us how  to input ChatGPT API key? It keep failing.

### ISSUE THREAD

**Issue by researchwong** [Makememo/MemoAI#159]
Could you guide us how to input ChatGPT API key? Because many features requires ChatGPT API key which I don't know how to use.
![image](https://github.com/Makememo/MemoAI/assets/155805861/12c82a74-c717-49f8-bf58-ef06edfee990)

I want to use the mindmap and summaries features.

**Comment by Sircam19** [comment]
Hello. I got it to work on my machine but I do remember having a few issues at first. I believe I tried removing the SK prefix and that should be good. Interested to see if it works for you afterwards :-)

**Comment by researchwong** [comment]
Hi,

I'm on a subscription for OpenAI, hoping Memo is able to make it works. gpt4 is a requirement. Hope u can integrate it. It's currently not working. I wish to have a video tutorial on how to get it work.

first try:
I've remove the SK prefix, but it still doesn't work
![image](https://github.com/Makememo/MemoAI/assets/155805861/1c756b52-1666-40af-b170-1df335018646)

Second try:
I try to leave both boxes blank too , translating failed.
![image](https://github.com/Makememo/MemoAI/assets/155805861/6b4eab49-6253-4266-b783-3bac0f27eebd)

Third try:

![image](https://github.com/Makememo/MemoAI/assets/155805861/a0f81ec3-8bc2-4ca8-9ff4-2d5337f803fe)
Secret key that is require i've already input 
URL: https://platform.openai.com/api-keys
secret key taken from here
![image](https://github.com/Makememo/MemoAI/assets/155805861/0db353c7-71b2-4a3f-8de4-b16a8f0e6eb9)

**Comment by Makememo** [comment]
Do you have a pre-recharge Open AI?

**Comment by Makememo** [comment]
Go to Settings - Integrated Upgrade OpenAI Addons.

**Comment by researchwong** [comment]
Hi Memo,

Can we  integrate with freeversion of ChatGPT instead? why do we need API
version?

**Comment by researchwong** [comment]
Could you provide option for free AI service, like free chatGPT will do...
like how
YouTube Summary with ChatGPT & Claude <https://glasp.co/youtube-summary>  ,
they have a option to use free version to summaries video. May I request to
have this on memo too? We need free version
