### ISSUE TITLE
进度卡在99

### ISSUE THREAD

**Issue by HuLuXi** [Makememo/MemoAI#16]
在识别一个一个小时左右的视频时，进度卡在99很久，一直不变，然后我看识别进度已经完成了，整个音轨都识别到了，但是卡在99，无法导出，其他功能都是好的，点击停止没反应，也没有提示。关闭后只能重新识别

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win10
 - Browser edge

**Additional context**

**Comment by Makememo** [comment]
是否有在设置 - 实验室启用 GPU？

**Comment by HuLuXi** [comment]
> 是否有在设置 - 实验室启用 GPU？

启用gpu加速了

然后我发现，重新打开然后再用原来的模型，还是可以加载缓存的，就是还是重新走一遍流程，但是比之前快很多很多，但也要五六分钟，然后恢复之前的进度之后就完成了
就是有没有会话框提示直接恢复缓存这样类似的功能呢？？

**Comment by Makememo** [comment]
收到，我们优化一下。

**Comment by Makememo** [comment]
已经更新：https://memo.ac/releases
