### ISSUE TITLE
希望增加小牛翻译

### ISSUE THREAD

**Issue by DavidJoyDong** [Makememo/MemoAI#161]
希望增加小牛翻译
https://niutrans.com/

**Comment by Makememo** [comment]
![2024-01-11234441@2x](https://github.com/Makememo/MemoAI/assets/140973261/61535afe-475f-4339-b254-719335a67116)
我们兼容一下，看起来价格和策略还是火山更好一些。

**Comment by Makememo** [comment]
集成 - 插件中下载配置。https://github.com/Makememo/MemoAI/releases/tag/v1.1.6
