### ISSUE TITLE
 Screen Flickering Issue on Specific Video Pages

### ISSUE THREAD

**Issue by Qifull** [Makememo/MemoAI#166]
Hello,

I've encountered a screen flickering issue with the Memo software, where my computer screen starts flickering uncontrollably on certain video pages within the application. This problem seems to recur on multiple videos, significantly hindering the usability of the software. I've detailed the issue and my system configuration below.

Issue Details
Software Version: Memo (Latest Version)
System Specifications: Windows 11  (Latest Version)
CPU: AMD Ryzen 9 7950H
GPU: NVIDIA RTX 4060

Frequency of Occurrence: The issue occurs every time I navigate to specific video pages within the Memo software.

**Comment by Makememo** [comment]
Can you record a video to see the effect?

**Comment by Qifull** [comment]
Maybe it is my setup problem, sorry for this issue
