### ISSUE TITLE
长视频转写出现时间点对不上和后面转写失败的情况

### ISSUE THREAD

**Issue by Qifull** [Makememo/MemoAI#169]
我使用该软件的时候转写一个时间长度高达四个小时的视频，前面还是正常的。但是到四五十分钟就开始出问题了。不仅时间点对不上而且转译没有完成就默认成功。 视频后面的字幕也没有了。试了几次都是这样
<img width="384" alt="image" src="https://github.com/Makememo/MemoAI/assets/137274199/86e1b9ac-aaf5-481c-a0c9-f53fc90fbb75">

**Comment by Makememo** [comment]
还在排查此问题，争取下个版本修复。

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/releases/tag/v1.3.3 

- When transcribing, select cuda mode for GPU mode
- Go to Settings-Lab-Turn on the flash attention mechanism switch
--
- 轉寫時，GPU 模式選擇 cuda 模式
- 前往設置 - 實驗室 - 打開 flash attention 機制開關
