### ISSUE TITLE
TRANSLATOR CONNECT TIMEOUTS/ERROR

### ISSUE THREAD

**Issue by bearrr97** [Makememo/MemoAI#178]
The AI translator is not working.
It was fine when I first used it, but it does not work for me after 2 days

![image](https://github.com/Makememo/MemoAI/assets/158485567/5ae14419-16dc-40f5-bbb4-b1b4aee64b5e)

**Desktop (please complete the following information):**
 - OS: [e.g. window 11]
 - Model[e.g. medium]
 - Version [e.g. 1.1.6]

**Comment by Makememo** [comment]
Please close the agent.

**Comment by bearrr97** [comment]
What to you mean agent?

**Comment by bearrr97** [comment]
> Please close the agent.

im sorry, I can't get it, what do you mean agent?

**Comment by Makememo** [comment]
网络问题，关掉翻墙软件。
