### ISSUE TITLE
可否增加字幕自动合并被断开的句子的功能？

### ISSUE THREAD

**Issue by zj1123581321** [Makememo/MemoAI#18]
## 背景

在音频转文字的准确率上，OpenAI 的 Whisper + Prompt 远超一般的模型服务(飞书妙记、通义听悟、讯飞...)，尤其是在专业名词较多的领域。

但 Whisper 的转写断句能力较差(Large v2 模型)，经常会出现一句话被分隔成两行字幕的情况。

根据 [openai-cookbook/examples/Whisper_prompting_guide.ipynb at main · openai/openai-cookbook](https://github.com/openai/openai-cookbook/blob/main/examples/Whisper_prompting_guide.ipynb) 所言，Whisper 的 Prompt 和 GPT 的 Prompt 并不完全一致——即 Whisper 的 prompt 并不理解 Prompt 所蕴含的指令含义，它只是在**模仿 Prompt 的语言风格和词汇拼写**。

所以通过 Prompt 很难完美解决 Whipser 转写句子被拆分的问题。

目前思考这个问题有两种解决方案：

1.  上传 srt 给 claude，让其返回合并句子后的 srt 文件。
2.  通过代码按某些规则来合并 srt 文件中的句子。

1 是一种比较简单且理想的方案，因为大模型对语义有理解分析，其断句分段把握的比较合适。

但 1 的问题在于大模型有字符长度限制，实测超过 30 min 的转录文本进行合并分段会超出字符限制。初次之外，这种方案还有等待时间较长，可能会出现幻觉等问题。

我日常转录的是 3h 的课程录音，所以我选择采用方案 2 做断句修正。

## 实现策略

方案 2 的原理上比较简单：

> 判断当前行结尾是否有标点符号，如果没有则和下一组字幕文本合并。

## 脚本内容

[zj1123581321/Adjust_SubTitle: 调节 Whisper 转录生成的 srt 文件，避免一句话被分成两行，避免一句话过短。](https://github.com/zj1123581321/Adjust_SubTitle)

目前我的解决方案是先用 Memo 转写，然后导出 Srt 字幕，运行脚本合并断行，最后再重新导入到 Memo 里。

过程有点繁琐，希望 Memo 能把脚本功能集成在软件里，会方便很多。

**Comment by Makememo** [comment]
Win GPU 模式下不支持，其他情况下已经支持断句能力。可以查阅：https://memo.ac/releases.html#_2023-09-04-v1-0-6-beta

**Comment by zj1123581321** [comment]
windows 下不用 GPU 加速转写好慢。。

如果 srt 的断句处理方式是在转录完成后修改 srt 文件，那原则上就不受转录方式影响了？

这样灵活性也比较高。
- 可以恢复断句为一行
- 可以保证每行结尾不为逗号
- 可以控制每一行的长度在区间范围值内。

每天我都用 Memo 转写课程录音，每次都是需要 srt 导出再重新导入，实在是有点折磨。。

或者是否有可以直接操纵转录 srt 文件的方式？

**Comment by Makememo** [comment]
windows GPU 已经支持断句。
