### ISSUE TITLE
Cantanose voice video output problem

### ISSUE THREAD

**Issue by topherlau** [Makememo/MemoAI#180]
**Describe the bug**
when i select a cantonese video to transcribe., it output as english.  sometimes the speaker say english in the video. If i use the auto detect , it will give Simplfied Chinese , but not cantonese  

**Desktop (please complete the following information):**
 - OS macOS 14]
 - Model[e.g. Tiny medium Large]
 - Version [e.g. 1.1.6]

**Additional context**

**Comment by Makememo** [comment]
Cantonese Only support by large v3 modles.
