### ISSUE TITLE
批量转写无法批量导出文字，需要一个个选择导出，很累的。

### ISSUE THREAD

**Issue by lightmandavie** [Makememo/MemoAI#183]
批量转写无法批量导出文字，需要一个个选择导出，很累的。

**Comment by Makememo** [comment]
请转写面板设置导出文件夹。

**Comment by lightmandavie** [comment]
明白了，我想同时 导出2个格式，如 STR 和 TXT  可以吗？

人工修改字幕后，可以批量导出吗？
________________________________
发件人: Memo AI ***@***.***>
发送时间: 2024年2月16日 9:40
收件人: Makememo/MemoAI ***@***.***>
抄送: lightmandavie ***@***.***>; Author ***@***.***>
主题: Re: [Makememo/MemoAI] 批量转写无法批量导出文字，需要一个个选择导出，很累的。 (Issue #183)


请转写面板设置导出文件夹。
