### ISSUE TITLE
选择 粤语 后无论选择哪一个模型都无法成功转写，是为什么？

### ISSUE THREAD

**Issue by lightmandavie** [Makememo/MemoAI#184]
选择 粤语 后无论选择哪一个模型都无法成功转写，是为什么？

**Comment by Makememo** [comment]
粤语仅支持 V3，windows v3 后续支持。

**Comment by lightmandavie** [comment]
V3 不是灰色吗？
________________________________
发件人: Memo AI ***@***.***>
发送时间: 2024年2月16日 9:39
收件人: Makememo/MemoAI ***@***.***>
抄送: lightmandavie ***@***.***>; Author ***@***.***>
主题: Re: [Makememo/MemoAI] 选择 粤语 后无论选择哪一个模型都无法成功转写，是为什么？ (Issue #184)


粤语仅支持 V3，windows v3 后续支持。

―

**Comment by Makememo** [comment]
#185 Repeat.
