### ISSUE TITLE
最大的模型3.0下载后，选项一直是灰色，无法调用是为什么？

### ISSUE THREAD

**Issue by lightmandavie** [Makememo/MemoAI#185]
最大的模型3.0下载后，选项一直是灰色，无法调用是为什么？

**Comment by Makememo** [comment]
还未开发支持。

**Comment by lightmandavie** [comment]
好的 知道了
________________________________
发件人: Memo AI ***@***.***>
发送时间: 2024年2月16日 9:39
收件人: Makememo/MemoAI ***@***.***>
抄送: lightmandavie ***@***.***>; Author ***@***.***>
主题: Re: [Makememo/MemoAI] 最大的模型3.0下载后，选项一直是灰色，无法调用是为什么？ (Issue #185)


还未开发支持。

―
