### ISSUE TITLE
Transcription error with MacBook Pro with Chip M1 Pro

### ISSUE THREAD

**Issue by loveunk** [Makememo/MemoAI#186]
**Describe the bug**

**To Reproduce**
1. I tried Transcribe with CoreML, but encoutered error, it stops with no transribtion results. The model I used is `Distil-large-v2`.
2. Then, I tried transcribe with CPU, it works.
3. After the transcription, I find some issues with the results. 
4. Here's one example, around 15-seconds' audio is not transcribed.
<img width="736" alt="image" src="https://github.com/Makememo/MemoAI/assets/1678567/45ad3837-de05-435b-966f-d617f72c4ef6">

**Expected behavior**

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: 14.2.1
 - Model: Distil-large-v2
 - Version: 1.1.6 (1.1.6)

**Additional context**

**Comment by Makememo** [comment]
Distil-large-v2 is not recommended. There are many bugs. It is recommended to use medium.en, which can meet most scenarios.

**Comment by loveunk** [comment]
> Distil-large-v2 is not recommended. There are many bugs. It is recommended to use medium.en, which can meet most scenarios.

Thank you, I will try it later.
