### ISSUE TITLE
翻譯設定為繁體中文，但Open AI實際上翻譯出來的常常會是簡體中文。但MemoAI介面沒有地方可以做批次修改。

### ISSUE THREAD

**Issue by brianforest** [Makememo/MemoAI#187]
翻譯設定為繁體中文，但Open AI實際上翻譯出來的常常會是簡體中文。但MemoAI介面沒有地方可以做批次修改。
(可以匯出SRT字幕，但轉換成繁體中文後， SRT字幕 沒有地方可以重新匯入)

**Comment by brianforest** [comment]
除了字幕無法匯入形成黑盒子效應之外，轉入的YouTube原始視頻檔案也找不到存放的路徑

**Comment by Makememo** [comment]
Let's take a look at the subsequent test optimization.

**Comment by Makememo** [comment]
已经支持更改提示词，可以改一下提示词。
