### ISSUE TITLE
建议更换 Google Translate API 为免费 Get 版本的

### ISSUE THREAD

**Issue by zj1123581321** [Makememo/MemoAI#19]
**Is your feature request related to a problem? Please describe.**
目前 Memo 内嵌的 Google Translate 接口经常会提示此 IP 调用频繁，导致不能正常翻译。

**Describe the solution you'd like**
使用 [Found a Google Translate endpoint that doesn't require an API key. · Issue #268 · ssut/py-googletrans](https://github.com/ssut/py-googletrans/issues/268) 所言的免费 Google Translate API 接口(Get)

```
"https://translate.googleapis.com/translate_a/single?client=gtx&dt=t + params"
// where the params are:
{
  "sl": source language,
  "tl": destination language,
  "q": the text to translate
}
```
这个接口也是广大翻译软件中 Google Translate 的实现方法。调用频率完全可以满足个人使用的需求。
![Chrome 拓展 沉浸式翻译的 Google Translate](https://github.com/Makememo/MemoAI/assets/33171229/9cf239bd-2cbe-4f4c-ae01-af3cac0f1834)

**Comment by Makememo** [comment]
下个版本优化。
