### ISSUE TITLE
關於字幕的一連串問題

### ISSUE THREAD

**Issue by brianforest** [Makememo/MemoAI#191]
1. 在調整中英雙字幕大小及顏色後, 預覽正常, 但轉檔後中英字幕位置跑掉 (重疊)
2. 調整中英雙字幕大小及顏色後, 從此轉檔過程非常緩慢，轉出檔案非常肥大 (原始48MB, 會產生兩個超大檔案 (791.7MB 無字幕, 753.6MB 有雙字幕但重疊)
3. 不知道為何要將組織幕強制設為中文？明明字幕檔是英文為先，中文為後？而且還無法上下對調

<img width="921" alt="Screenshot 2024-02-22 at 23 20 46" src="https://github.com/Makememo/MemoAI/assets/160719719/72d4b8b6-b84a-40af-a0df-c1fdc5665a5a">
<img width="1710" alt="Screenshot 2024-02-22 at 23 49 19" src="https://github.com/Makememo/MemoAI/assets/160719719/c9aa1e0c-62eb-4728-a398-e6fc200e4519">
<img width="1710" alt="Screenshot 2024-02-22 at 23 23 12" src="https://github.com/Makememo/MemoAI/assets/160719719/f417b74d-14f9-4d60-9f8c-b99a7f078fc3">

**Comment by brianforest** [comment]
<img width="1710" alt="Screenshot 2024-02-22 at 23 49 19" src="https://github.com/Makememo/MemoAI/assets/160719719/59680ed1-57a4-413e-9912-2b35ea4a9d65">

<img width="1710" alt="Screenshot 2024-02-22 at 23 23 12" src="https://github.com/Makememo/MemoAI/assets/160719719/7730cab7-1bd4-4f1b-9185-441323040bdc">

**Comment by Makememo** [comment]
Please go to update version 1.1.7, which supports export and subtitle adjustment. https://github.com/Makememo/MemoAI/releases/tag/v1.1.7
