### ISSUE TITLE
一些不成熟的功能想法

### ISSUE THREAD

**Issue by Geo123abc** [Makememo/MemoAI#2]
1. 支持导出为markdown格式的笔记（很多软件都兼容markdown笔记导入，比如obsidian、思源笔记），方便与已有工作流融合。
2. 时间戳支持变量、自定义模板，（这种就和从浏览器获得时间一致）

    1. 引入{{当前播放时间_秒}} 、{{当前播放时间_时分秒}}、{{视频名字}}变量
    2. 自定义模板，比如markdown格式，`[提示词](https://www.bilibili.com/video/{{视频名字}}/?t={{time}})`，如果我下载一个B站视频，文件名设置为BV番号`BV1hS4y137wt`，此时插入的时间戳是`[@02:24](https://www.bilibili.com/video/BV1zF411Z7ap/?t=143)`，即：[[@02:24](https://www.bilibili.com/video/BV1zF411Z7ap/?t=143)](https://www.bilibili.com/video/BV1zF411Z7ap/?t=143)
3. 播放、暂停、倍速、快进等支持快捷键，可以参考potplayer的设置；

**Comment by Makememo** [comment]
感谢反馈，非常好的建议，我们归纳一下安排迭代相关。
