### ISSUE TITLE
TTS 推荐

### ISSUE THREAD

**Issue by Geo123abc** [Makememo/MemoAI#20]
v1.0.7 的 文字转语音好像使用的是在线的服务，时候考虑使用一些离线的模型？比如

[枫语云心bert-vits2一键使用工具来了|完全免费的文字转语音工具_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1s14y1C7h3)    

[Stardust-minus/Bert-VITS2: vits2 backbone with bert](  https://github.com/Stardust-minus/Bert-VITS2  )  

[vits-simple-api/README_zh.md at main · Artrajz/vits-simple-api](  https://github.com/Artrajz/vits-simple-api/blob/main/README_zh.md  )     

[VALL-E-X/README-ZH.md at master · Plachtaa/VALL-E-X](  https://github.com/Plachtaa/VALL-E-X/blob/master/README-ZH.md  )    
VALL-E X 配备有一系列尖端功能：
多语言 TTS: 可使用三种语言 - 英语、中文和日语 - 进行自然、富有表现力的语音合成。
零样本语音克隆: 仅需录制任意说话人的短短的 3~10 秒录音，VALL-E X 就能生成个性化、高质量的语音，完美还原他们的声音。

**Comment by Makememo** [comment]
thanks!
