### ISSUE TITLE
增加 gpt-3.5-turbo 和 gpt-4-turbo-preview 模型

### ISSUE THREAD

**Issue by devyujie** [Makememo/MemoAI#201]
官网显示 gpt-3.5-turbo 已指向**最新**的 0125 模型，**16k** 上下文：
![image](https://github.com/Makememo/MemoAI/assets/48620527/100f21a0-2cae-4421-83a7-456b8c71e3af)

gpt-4-turbo-preview 也**始终**指向 4turbo 的后续更新模型，**128k** 上下文：
![image](https://github.com/Makememo/MemoAI/assets/48620527/431097b1-63eb-4b38-ac38-a99305c44574)

两个都是最新的模型，请求支持一下，既能降低成本，又能增加转译质量。
![image](https://github.com/Makememo/MemoAI/assets/48620527/a43d0c8e-2dae-480f-b08c-2e94113fe4dd)

**Comment by Makememo** [comment]
设置 - 集成 - Open AI 插件更新一下，用这个。
