### ISSUE TITLE
The transcribed japanese text is not using japanese kanji 日语转译的文本不是日语汉字

### ISSUE THREAD

**Issue by VictorNanka** [Makememo/MemoAI#202]
**Describe the bug**

For example:
过去资料 should be 過去資料

but the model give the simplified Chinese character

**To Reproduce**
You can try any Japanese Video

**Expected behavior**
The generated text should be restricted to the Japanese kanji

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 14
 - Model[e.g. Medium]
 - Version [e.g. 1.1.8]

**Additional context**

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/releases/tag/v1.1.9 It has been fixed
