### ISSUE TITLE
说话者识别

### ISSUE THREAD

**Issue by eatgrass** [Makememo/MemoAI#208]
能支持下Speaker diarization吗

**Comment by linmi** [comment]
1.2.1 上线。

**Comment by Makememo** [comment]
1.2.1 上线

**Comment by aantior** [comment]
![Uploading image.png…]()
抱歉没找到在哪里用呀？

**Comment by aantior** [comment]
ding一下，没找到在哪里

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/releases/tag/v1.3.1
