### ISSUE TITLE
使用claude翻译出现403错误

### ISSUE THREAD

**Issue by devyujie** [Makememo/MemoAI#209]
claude账户状态是好的，api key也可以用，不知道为什么。

![image](https://github.com/Makememo/MemoAI/assets/48620527/b47344ba-ef9c-4edc-9cd1-5a5437bfb311)

![image](https://github.com/Makememo/MemoAI/assets/48620527/25f4be57-31cb-46b8-bd75-91373febd3e1)

![image](https://github.com/Makememo/MemoAI/assets/48620527/a7c71b50-149c-430b-a10b-380e1d8362e5)

**Comment by Makememo** [comment]
![Uploading CleanShot 2024-03-13 at 17.55.40@2x.png…]()
