### ISSUE TITLE
Change lang from Chinese to English, the download task component did not update the translation

### ISSUE THREAD

**Issue by hawtim** [Makememo/MemoAI#21]
**Describe the bug**

Change lang from Chinese to English, the download task component did not update the translation

**To Reproduce**

1. use 简体中文 when the first time you use memo
2. try to switch lang from 简体中文 to English
3. it still remains 简体中文
![image](https://github.com/Makememo/MemoAI/assets/11072796/720948fb-d40b-42d9-a5c8-0585cfa25c79)

**Expected behavior**

- switch to English

**Screenshots**

as shown above.

**Desktop (please complete the following information):**

 - OS: MacOS Sonoma
 - Version v1.0.7

**Additional context**

- none

**Comment by Makememo** [comment]
Thanks, Next version fix.

**Comment by svpermari0** [comment]
@Makememo I bought Ultra. :)

**Comment by Makememo** [comment]
> @Makememo I bought Ultra. :)我买了超。 :)

Huge thanks for your support. Can I help you?

**Comment by svpermari0** [comment]
@Makememo Locale issue still on 1.0.9:
![image](https://github.com/Makememo/MemoAI/assets/17409586/298a7314-f105-4126-a8cf-d76c247e8d9f)
![image](https://github.com/Makememo/MemoAI/assets/17409586/9e28e821-4661-401a-a89f-f8f39e48b800)

**Comment by svpermari0** [comment]
I assume that first image, ain't supposed to be Chinese for me? 😊
Forgive me for not knowing the dialect!

**Comment by Makememo** [comment]
> I assume that first image, ain't supposed to be Chinese for me? 😊我认为第一张图片对我来说不应该是中国的吗？ 😊 Forgive me for not knowing the dialect! 原谅我不懂方言！

Refactoring to this point step by step.

**Comment by Makememo** [comment]
请使用批量转写。
