### ISSUE TITLE
编辑转写字幕，自动跳转到行尾

### ISSUE THREAD

**Issue by p3psi-boo** [Makememo/MemoAI#210]
**Describe the bug**
转写得到字幕后，尝试编辑转写字幕：
1. 输入一个字符后，会像卡住一样，然后光标会自动跳转到行尾，然后在选中位置出现输入的字符
2. 如果输入多个字符，会卡住而后跳转到行尾，而后续的字符只会有一个追加到行尾。
3. 按 Backspace 键3次，只会删除一个字符。

**Expected behavior**
流畅的编辑转写字幕，且光标不会跳到行尾

**Screenshots**

问题1的录屏：
![问题1的录屏](https://github.com/Makememo/MemoAI/assets/43925055/afd7b78d-b922-4dd3-9224-4b25a9c3f709)

问题2的录屏：（这里输入了 ueu，打算补全 Queue 单词）
![问题2的录屏](https://github.com/Makememo/MemoAI/assets/43925055/de163c05-1502-4a14-b9d7-8c2399c17147)

问题3的录屏：（这里按了 Backspace 三次，但只触发了一次）
![问题3的录屏](https://github.com/Makememo/MemoAI/assets/43925055/a34978ab-afc6-446f-ba69-207d13b418ce)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Model: Base.en
 - Version: 1.20.0

**Comment by Makememo** [comment]
下个版本修复，感谢反馈。

**Comment by Makememo** [comment]
It has been solved. Https://github.com/Makememo/MemoAI/releases/tag/v1.2.1, please download it here.
