### ISSUE TITLE
Can not move the sub on the screen

### ISSUE THREAD

**Issue by InitialQD** [Makememo/MemoAI#213]
**Is your feature request related to a problem? Please describe.**
When I wanted to add Chinese sub to a video which already featured English sub (I can't remove English sub, it's built in the video). I need to leave some space between those 2 languages, but there is no such function to do so. As the result the Chinese sub and English sub are overlapping.
![微信图片_20240315145532](https://github.com/Makememo/MemoAI/assets/163504427/00e80d6a-95a6-444b-b85f-70c5b356fb96)

**Describe the solution you'd like**
It would be better if I can move the subs  higher or lower on the screen, and I can adjust the size of word in a greater range, like from size 6 to 20.

**Describe alternatives you've considered**

**Additional context**

**Comment by Makememo** [comment]
[Croatian](https://github.com/Makememo/MemoAI/releases/tag/v1.3.1)
