### ISSUE TITLE
transcribe youtube videos failed on Windows client

### ISSUE THREAD

**Issue by ehowang** [Makememo/MemoAI#214]
**Describe the bug**

 After I input the youtube links and configure language,model,CPU/GPU stuff, then I click the transcribe button and it indeed downloading.
![image](https://github.com/Makememo/MemoAI/assets/57342585/210cef1d-d994-4658-981e-7dba563343fb)
But then a window pop up showing download error.
![image](https://github.com/Makememo/MemoAI/assets/57342585/e96bd9fd-4240-4269-8a66-e2c30e9f16e5)

**To Reproduce**
1、input youtube links
2、select language:english ,model:medium.en,and gpu speed up
3、click the transcribe button
4、transcribing then error occured

**Expected behavior**
I expected it to work well, transcribing video to text

**Desktop (please complete the following information):**
OS: Winwdows10
Model:medium.en
Version:1.2.0

**Comment by Makememo** [comment]
Please try the new version Https://github.com/Makememo/MemoAI/releases/tag/v1.2.1
