### ISSUE TITLE
自動儲存功能，降低了編輯字幕的效率

### ISSUE THREAD

**Issue by itshanyu** [Makememo/MemoAI#217]
**Describe the bug**
自動儲存功能造成修正字幕（打字、刪除字）時會 LAG 很多秒，之前都不會這樣

**To Reproduce**
刪除字時，即使選了從中間的字開始刪除，卻因為自動儲存功能，會自動從最後的字開始刪除
打字時，只打一個注音字，就會自動儲存，造成字無法完整打完，需要從別的軟體打好之後，再貼過來

**Expected behavior**
取消隨時自動儲存的功能，用戶可以自行決定什麼時候要儲存檔案

**Screenshots**
https://jam.dev/c/78d52190-1edc-4321-ab08-cc8389d9b983

**Desktop (please complete the following information):**
Timestamp
2024年3月17日 上午11:19 [GMT+8]
OS: Windows (x86) 11
Window size: 2505x1284
Country: Taiwan 🇹🇼

**Additional context**

**Comment by Makememo** [comment]
今天修复，很抱歉出现这样的问题。

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/releases/tag/v1.2.1 请前往这里下载即可。

**Comment by itshanyu** [comment]
沒問題了，非常感謝！
