### ISSUE TITLE
批量转换没有批量生成srt文件的选项

### ISSUE THREAD

**Issue by aantior** [Makememo/MemoAI#219]
![image](https://github.com/Makememo/MemoAI/assets/131586786/b1427b55-d263-4433-b7b4-e2c1f2a40f9a)

希望能够选择自动生成srt文件

**Comment by Makememo** [comment]
![P2024-03-18 at 23 40 30@2x](https://github.com/Makememo/MemoAI/assets/140973261/aba50d93-d998-4f75-affa-57ea1a503c66)
