### ISSUE TITLE
show the download task progress

### ISSUE THREAD

**Issue by hawtim** [Makememo/MemoAI#22]
**Is your feature request related to a problem? Please describe.**

I started downloading a video and I could not get the progress information, it made me worry about my network quality, or maybe something was wrong.

![image](https://github.com/Makememo/MemoAI/assets/11072796/bb0acdae-495f-4dd7-8bea-d0aa0754171c)

**Describe the solution you'd like**

I can see the download task progress and if something is wrong, I can troubleshoot ASAP.

**Describe alternatives you've considered**

I think it could be a number or a progress bar.

**Comment by Makememo** [comment]
已经迁移至批量能力中，请点击 personal 旁边 ➕ 新建。
