### ISSUE TITLE
English Docs Suggestions

### ISSUE THREAD

**Issue by candideu** [Makememo/MemoAI#223]
Hello! I wasn't able to edit the docs directly because the edit button leads to a 404 page:

![image](https://github.com/Makememo/MemoAI/assets/55474996/1e888c98-1cc9-4406-bd32-d43643ac40b6)

![image](https://github.com/Makememo/MemoAI/assets/55474996/471655ab-d09e-4295-85f4-f9cd4cf182ea)

As such, I'll add my suggestions for the English docs below:

1. ~~[Introduce](https://memo.ac/start-here.html#introduce)~~ -> Introduction

2. ~~[Links transcribe](https://memo.ac/start-here.html#links-transcribe)~~ -> Import media from external sites

3. ~~[Memo AI supports the rewriting of links to Youtube and Apple Podcast. Support links](https://memo.ac/start-here.html#links-transcribe)~~ -> Memo AI can transcribe media hosted on Youtube, Apple Podcast, Xiaoyuzhoufm and more. It's currently compatible with the following URLs: 

4. ~~[Local transcribe](https://memo.ac/start-here.html#local-transcribe)~~ -> Transcribe local files

5. ~~[Memo local conversion supports MP4, MP3, AAC, M4A and other common audio and video formats, and there is no need to convert the format before uploading to text. Note that there are no special characters in the local conversion name, otherwise Memo cannot be read.](https://memo.ac/start-here.html#local-transcribe)~~ -> MemoAI can transcribe local files in audio and video formats such as MP4, MP3, AAC, M4A, etc. without the need for conversion. Please note that the name of the file to be converted should not contain special characters, otherwise MemoAI will not recognize it.

6. ~~[If you already have local subtitles and just need translation ability, please click to upload subtitles. SRT and VTT formats are currently supported.](https://memo.ac/start-here.html#local-transcribe)~~ -> If you already have a subtitle file and only need to translate it, you can upload the file directly. We currently support SRT and VTT formats.

7. ~~[You need to go to these websites to apply for Key and paste it into Memo to use.](https://memo.ac/start-here.html#ai-translation)~~ -> You will need to acquire an API key from the official websites to use these services in Memo.

8. ~~[If you can't translate, please check the network first, then check if the content is too long, and then check if there is any arrears in Key](https://memo.ac/start-here.html#ai-translation).~~ -> If you find that you can't translate, first check the network condition, then see if the content is too long, and finally check if the API key and usage limits are okay.

9. ~~[Support a variety of speech synthesis, other languages can also listen fluently.](https://memo.ac/start-here.html#ai-tts).~~ -> We support a variety of speech synthesis methods, and other translated languages can be dubbed over the original media.

10. ~~[Memo Support the export of SRT, VTT and other subtitle formats to help you save the tediousness of manual scrolling. Tools such as Markdown also support export synchronously.](https://memo.ac/start-here.html#export-text-and-subtitles)~~ -> Memo supports exporting common subtitle formats such as SRT, VTT, etc., eliminating the need for manual adjustments. We also support synchronized export with Markdown and other tools.

**Comment by Makememo** [comment]
Let's migrate. Thank you for your help.
