### ISSUE TITLE
Suggestions for multilingual subtitles and multiple caption files - Side-by-side viewing and editing

### ISSUE THREAD

**Issue by candideu** [Makememo/MemoAI#225]
I really love what has been done so far with the translations and auto-dubbing. Very few captioning apps support this, so it's great that you've included it for multilingual support.

My suggestion / feature request has to do with the way bilingual captions are currently handled.

Right now, the subtitles come one after the other in the editor:

![image](https://github.com/Makememo/MemoAI/assets/55474996/c69f0f76-ca84-43de-9409-b4850ca97fba)

That said, I would also like to see an option where both (or multiple) languages / captioning files can be displayed side-by-side, and selected via a dropdown.

The [Amara Editor's interface](https://amara.org/) is a good example of this:

![image](https://github.com/Makememo/MemoAI/assets/55474996/41016030-eefa-4324-bbe5-b426d81b1c0c)

This could also be helpful for multiple caption files of the same language. For example, maybe I generated automatic captions using YouTube, Deepl, and Open AI, and I want to compare them side-by-side while playing back my media to see which file to use.

**Comment by Makememo** [comment]
![P2024-03-19 at 23 39 15@2x](https://github.com/Makememo/MemoAI/assets/140973261/ce4eb6ce-2094-425e-b5d5-1fcd18499e43)
![P2024-03-19 at 23 39 23@2x](https://github.com/Makememo/MemoAI/assets/140973261/69237da7-4b5b-445d-ba20-6763c1529a7d)

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/assets/140973261/9942092e-b42e-474f-b8c3-a8881039a569

**Comment by candideu** [comment]
Looks great, just tested it out on my end! I'll close this for now. Thank you!
