### ISSUE TITLE
无法上传本地视频

### ISSUE THREAD

**Issue by hx3333** [Makememo/MemoAI#226]
**Describe the bug**
打开软件无法上传本地视频mp4格式，软件没有任何响应和提示

**To Reproduce**
查看日志，报错Error: ffmpeg exited with code 1: No decoder for stream #0:0, filtering impossible
Error configuring complex filters.

**Expected behavior**
希望彻底修复bug，且前端能弹出报错提示

**Screenshots**
![image](https://github.com/Makememo/MemoAI/assets/44716826/5243f8a1-e5ab-4283-9a7a-2001282e9d9b)

**Desktop (please complete the following information):**
 - OS: win11
 - Version: 1.2.1

**Additional context**
上次有提过这个bug，好像还是没解决
https://github.com/Makememo/MemoAI/issues/74#issue-1999017140

**Comment by Makememo** [comment]
视频是有 VP9 编码么？

**Comment by hx3333** [comment]
是的，是VP09编码的

**Comment by Makememo** [comment]
VP09 试试新版本 1.2.2
