### ISSUE TITLE
转发API host调用失败

### ISSUE THREAD

**Issue by miaoduke** [Makememo/MemoAI#228]
https://github.com/chatanywhere/GPT_API_free 中的两个国内转发host调用失败
转发Host1: https://api.chatanywhere.tech (国内中转，延时更低，host1和host2二选一)
转发Host2: https://api.chatanywhere.com.cn (国内中转，延时更低，host1和host2二选一)

**Comment by Makememo** [comment]
这个需要您联系服务商解决，确认是否欠费或者域名写错。

以及 Memo 不会主动适配第三方服务。

**Comment by miaoduke** [comment]
感谢回复，
1.没有欠费，
2.域名没写错
3.有在其他应用长期调用，一直正常使用
