### ISSUE TITLE
一直卡在“启动转写中”，无限转圈ing

### ISSUE THREAD

**Issue by michael7908** [Makememo/MemoAI#229]
我的系统是Win11，主机配置如下（迷你电脑，集成主板）：

处理器：Intel(R) Celeron(R) N5095A @ 2.00GHz   2.00 GHz

机带RAM：16.0 GB (15.8 GB 可用)

请问：这个配置是不是太破了，所以跑不动任何模型？

该如何解决？（买新电脑也算）。

**Comment by Makememo** [comment]
AVX 指令集需要开启，建议换正常 i7 CPU

**Comment by SyberRabbit** [comment]
> AVX 指令集需要开启，建议换正常 i7 CPU

那thinkbook，r7-7735h呢，我第一次转写成功，之后再怎么尝试都是  启动转写中

**Comment by Makememo** [comment]
> > AVX 指令集需要开启，建议换正常 i7 CPU
> 
> 那thinkbook，r7-7735h呢，我第一次转写成功，之后再怎么尝试都是  启动转写中

设置 - 实验室 - 导出日志
