### ISSUE TITLE
从15秒开始之后的文字全部相同

### ISSUE THREAD

**Issue by sandycs-protoss** [Makememo/MemoAI#23]
用的是largev1模型。
这个里不能上图，如链接所示：
[https://storage.googleapis.com/taotio/memobug.jpg](url)

具体表现是英文视频转换完成后，从第15秒开始内容全部相同

**Comment by Makememo** [comment]
请先选择视频源语言，再右上角翻译。

**Comment by sdugoten** [comment]
預到一樣的問題, 前面完全沒有問題, 到最後面10分鐘左右, 全部一樣的內容, 你可以download 原檔試.

https://temp-file.org/ANOxf418CwZdAwe/file

我已經先選日本語為"视频源语言"

**Comment by Makememo** [comment]
![2023-09-27 at 10 10 35@2x](https://github.com/Makememo/MemoAI/assets/140973261/454f23c0-b369-4379-89e3-11c223c82599)
我加了提示词后正常了。

**Comment by sdugoten** [comment]
> ![2023-09-27 at 10 10 35@2x](https://user-images.githubusercontent.com/140973261/270840563-454f23c0-b369-4379-89e3-11c223c82599.png) 我加了提示词后正常了。

我想我找到解決方案.  請問你可不可以加 --temperature_increment_on_fallback  , --condition_on_previous_text  這2個switch?  因為解決方案在這裡

[https://blog.gdeltproject.org/experiments-with-whisper-asr-model-parameters-non-determinism-temperature_increment_on_fallback/](url)

[https://github.com/openai/whisper/pull/1253](url)

應該加了這2個switch 後, 我會直接付費買lifetime 版.  謝啦.

**Comment by Makememo** [comment]
OK，后续会把参数开放开来。

**Comment by sdugoten** [comment]
> OK，后续会把参数开放开来。

另外, 好像提示詞跟whisper 有點不一樣.  我在whisper  加入這句 "以下係香港嘅港式廣東話", 片段內容是廣東話的話, 會直接輸出廣東話, 不過在memo 用一樣的提示詞, 輸出還是會翻譯成正體書面語.

**Comment by Makememo** [comment]
已经上线。https://memo.ac/releases.html

**Comment by sdugoten** [comment]
1.   --temperature_increment_on_fallback , --condition_on_previous_text 這2個switch在那找到?
2. 提示詞輸入 "以下係香港嘅港式廣東話" 仍然不會顯視video 內的廣東話, 直接翻譯成中文

**Comment by sdugoten** [comment]
看來人声检测提取（实验功能）好像解決我之前給你們那個video 的問題.  我另外再開一個新的issue 關於上面point 2 的提示詞問題
