### ISSUE TITLE
翻译插件消失&无法进行转录

### ISSUE THREAD

**Issue by grubs745** [Makememo/MemoAI#234]
从昨天起memo突然出现进入翻译插件页面显示为空，且进行视频转录（无论是本地视频还是YouTube视频）会卡住无法进行。

翻译插件页面为空：
<img width="671" alt="屏幕截图 2024-03-25 133737" src="https://github.com/Makememo/MemoAI/assets/68578516/70e43f19-f93d-4501-b9db-e8efa8a00ed7">
<img width="671" alt="屏幕截图 2024-03-25 133802" src="https://github.com/Makememo/MemoAI/assets/68578516/eea1a8d6-3944-4bde-a006-bff27a32f38c">

开始转写后，就会卡在如下界面：
<img width="899" alt="屏幕截图 2024-03-25 134020" src="https://github.com/Makememo/MemoAI/assets/68578516/62303b6b-8ff3-48fd-99b5-35ba35035b15">
此时，除了放大、缩小和关闭窗口外，界面上的所有按钮都是没有反应的。
尝试过本地视频和YouTube视频，模型尝试过Tiny和Large v2，CPU、GPU和cuBLAS模式都尝试过，均是如此。
同时，后台占用基本稳定：
<img width="587" alt="屏幕截图 2024-03-25 142117" src="https://github.com/Makememo/MemoAI/assets/68578516/f3e154f9-92b2-4ebd-9113-b03c0b872c54">
<img width="613" alt="屏幕截图 2024-03-25 142037" src="https://github.com/Makememo/MemoAI/assets/68578516/6c2f727a-b50a-4d8d-a586-8bd8acd72a04">

软件内的代理设置和模型情况如下：
<img width="673" alt="屏幕截图 2024-03-25 133834" src="https://github.com/Makememo/MemoAI/assets/68578516/dc8def17-6dbf-4173-8d6b-5827c80d153a">
<img width="671" alt="屏幕截图 2024-03-25 133914" src="https://github.com/Makememo/MemoAI/assets/68578516/4f78a05b-3388-4bc7-99df-1425d33add94">

网络环境：
<img width="868" alt="屏幕截图 2024-03-25 133556" src="https://github.com/Makememo/MemoAI/assets/68578516/33347fa4-e1d4-4c78-b43e-c9daa5ba4a0b">

设备和系统信息：
<img width="377" alt="屏幕截图 2024-03-25 134412" src="https://github.com/Makememo/MemoAI/assets/68578516/9caefb50-de7d-4326-a41d-0406724c059d">
<img width="355" alt="屏幕截图 2024-03-25 134448" src="https://github.com/Makememo/MemoAI/assets/68578516/8c14d01c-7dda-4721-988c-419af5df1f8c">
<img width="287" alt="屏幕截图 2024-03-25 134620" src="https://github.com/Makememo/MemoAI/assets/68578516/ef691263-82a2-4ea1-b3c8-ff4b643105cb">
<img width="211" alt="屏幕截图 2024-03-25 134823" src="https://github.com/Makememo/MemoAI/assets/68578516/72ea6c8f-746f-4d56-ab7a-960a791cb773">

日志文件：
[export_log.zip](https://github.com/Makememo/MemoAI/files/14739657/export_log.zip)

**Comment by Makememo** [comment]
C:\Users\shiju\AppData\Roaming\Memo\

进入这个文件下，把下面所有内容都删除。

然后这里下载导入。

"link":"https://plugins.memo.ac/translate/memo-plugin-translate-deepl@1.0.2.memox
"link":"https://plugins.memo.ac/translate/memo-plugin-translate-ollama@1.0.2.memox
"link":"https://plugins.memo.ac/translate/memo-plugin-translate-azure@1.0.3.memox
"link":"https://plugins.memo.ac/translate/memo-plugin-translate-claude@1.0.3.memox
"link":"https://plugins.memo.ac/translate/memo-plugin-translate-zhipuai@1.0.1.memox
"link":"https://plugins.memo.ac/translate/memo-plugin-translate-volctrans@1.0.2.memox
"link":"https://plugins.memo.ac/translate/memo-plugin-translate-tencent@1.0.3.memox
"link":"https://plugins.memo.ac/translate/memo-plugin-translate-openai@1.0.8.memox
"link":"https://plugins.memo.ac/translate/memo-plugin-translate-niutrans@1.0.3.memox
"link":"https://plugins.memo.ac/translate/memo-plugin-translate-gemini@1.0.5.memox
"link":"https://plugins.memo.ac/translate/memo-plugin-translate-microsoft@1.0.3.memox
"link":"https://plugins.memo.ac/translate/memo-plugin-translate-google@1.0.4.memox
"link":"https://plugins.memo.ac/translate/memo-plugin-translate-baidu@1.0.4.memox

**Comment by grubs745** [comment]
已解决，感谢
