### ISSUE TITLE
ASR 过程中会出现卡死情况

### ISSUE THREAD

**Issue by chenbd23** [Makememo/MemoAI#236]
![image](https://github.com/Makememo/MemoAI/assets/102299140/0d6f4bb3-e30a-4d78-b713-024842b136c9)
会出现都输出同一段文字，一直输出，然后过一段时间又会回复正常识别。好几个视频解析都出现过，开头一段正常，中间出现此类问题，后面又会回复

**Comment by chenbd23** [comment]
![image](https://github.com/Makememo/MemoAI/assets/102299140/77f76592-748b-44df-9875-b06509526823)
另外一个本地音频文件也是这样

**Comment by Makememo** [comment]
请选择中文专用模型，或者转录面板中，高级设置开启人声识别解决。

**Comment by chenbd23** [comment]
我已收到你的邮件，我会尽快回复。谢谢
