### ISSUE TITLE
Summary of transcript doesn't allow copy and paste

### ISSUE THREAD

**Issue by Sircam19** [Makememo/MemoAI#238]
**Describe the bug**
---

**Summary of transcript**  
无法复制和粘贴的摘要

Doesn't allow copy and paste.  
不允许复制和粘贴。  
I am unable to select the text such that it can be copied and pasted elsewhere.  
我无法选择文本以便将其复制和粘贴到其他地方。

**To Reproduce**  
重现步骤

1. Transcribe  
1. 转录  
2. Select summary  
2. 选择摘要  
3. Wait for summary  
3. 等待摘要  
4. Unable to interact with the summary text. It cannot be copied.  
4. 无法与摘要文本互动。它不能被复制。  

**Expected behavior**  
期望的行为

To copy and paste  
要复制和粘贴

**Screenshots**  
屏幕截图

如果适用，添加屏幕截图以帮助解释您的问题。

**Desktop (please complete the following information):**  
桌面（请完成以下信息）：

- OS: [e.g. macOS 14.4.1 Sonoma]  
- 操作系统：[例如 macOS 14.4.1 索诺玛]  
- Model[e.g. Large] All models  
- 型号[例如 大型] 所有型号  
- Version [e.g. 1.1.2] latest --> 1.2.1  
- 版本 [例如 1.1.2] 最新 --> 1.2.1

**Additional context**  
附加上下文

在此处添加有关问题的任何其他上下文。

https://github.com/Makememo/MemoAI/assets/4651001/c8220e0a-8b66-447a-a4a1-13d311359e6f

**Comment by Sircam19** [comment]
Please convert the following into simplified Chinese: Perhaps you can add the ability to export the summaries if easier. Also can you add a progress bar during the summarization and mind map process to help the user see how long the process will take /  也许你可以增加导出摘要的功能，如果这样更容易的话。同时，你能在总结和思维导图过程中添加一个进度条，以帮助用户看到过程需要多长时间吗？
![CleanShot 2024-03-27 at 20 51 51](https://github.com/Makememo/MemoAI/assets/4651001/88030ee8-d82b-4df7-8735-ae1f09b17dcd)
![CleanShot 2024-03-27 at 20 53 48](https://github.com/Makememo/MemoAI/assets/4651001/9fbe3eec-5697-4eba-adee-d5ea24698238)

**Comment by Makememo** [comment]
支持了。
