### ISSUE TITLE
翻译增加【Papago】选项，这个翻译韩语比较准确

### ISSUE THREAD

**Issue by yuehouqiyou** [Makememo/MemoAI#240]
翻译增加【Papago】选项，这个翻译韩语比较准确

这是韩国人的翻译器，https://papago.naver.com/
对比过所有翻译器 绝对比Google/MS 等免费翻译器准确，尤其是专门的名词
有时候甚至比付费的 openAI 更准确

**Comment by Makememo** [comment]
很抱歉，我们尝试注册了一下，发现条件比较严苛，无法获取到 API，后续有机会再适配。
