### ISSUE TITLE
导出视频有问题

### ISSUE THREAD

**Issue by Ranastclairy** [Makememo/MemoAI#244]
**Describe the bug**
导出视频时候，有提示正在导出，但是无法显示具体的导出进度，且导出的视频为0KB.
![image](https://github.com/Makememo/MemoAI/assets/96851060/ffc56a2e-59cd-4e3e-a5ce-82f13056717a)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 14]
 - Model[e.g. Large]
 - Version [e.g. 1.1.2]

**Additional context**

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/releases/tag/v1.3.3
