### ISSUE TITLE
Select a model for elevenlabs

### ISSUE THREAD

**Issue by oneevil** [Makememo/MemoAI#246]
Add the ability to select a model for elevenlabs:
- Eleven Multilingual v2
- Eleven Multilingual v1
- Eleven English v1
- Eleven Turbo v2

because the default model is Eleven English v1 :(

**Comment by Makememo** [comment]
![P2024-04-03 at 01 01 58@2x](https://github.com/Makememo/MemoAI/assets/140973261/1c524828-c532-455d-bb8c-3e02fc991a70)

Already supported, please go to the integration to upgrade.
