### ISSUE TITLE
導出繁體中文出現亂碼

### ISSUE THREAD

**Issue by andyhu67** [Makememo/MemoAI#251]
**Describe the bug**

 

**To Reproduce**
2. Click on ['....'](![螢幕擷取畫面 2024-04-10 100017](https://github.com/Makememo/MemoAI/assets/56128353/1017aa2e-d5e8-44f9-8b39-ca15b7134c4b))

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 14]
 - Model[e.g. Large]
 - Version [e.g. 1.1.2]

**Additional context**

**Comment by Makememo** [comment]
本地缺少字体，导出后是正常表现。
