### ISSUE TITLE
Subtitles/transcription not being generated in Windows 10.

### ISSUE THREAD

**Issue by kapilpandey0702** [Makememo/MemoAI#252]
**Describe the bug**
Subtitles/transcription not being generated in Windows 10.

**To Reproduce**
1. Go to 'Memo'
2. Click on 'Local file and uploaded video duration of 2 hours and 25 seconds'
3. Scroll down to 'Language --> Simplified Chinese | Select quality --> Memo-Large.zh | GPU --> CPU/GPU(Both tried)'
4. See error - First, it displays "Initiating transcription," then it goes blank.

**Expected behavior**
On my MacBook, I can see that on the right side, it is generating subtitles in simplified Chinese, but the same is not happening in Windows 10.

**Screenshots**
![image](https://github.com/Makememo/MemoAI/assets/110531964/331350ea-2fc0-40e4-9843-80a802139f61)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Model[e.g. Large]
 - Version [e.g. 1.1.2]

**Additional context**

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/releases/tag/v1.3.1
