### ISSUE TITLE
希望能將現有功能直接整合成文章翻譯功能

### ISSUE THREAD

**Issue by lloyd3126** [Makememo/MemoAI#256]
目前的逐字稿、翻譯、心智圖和 TTS 功能很好用！

希望能直接整成一個不是用來翻譯影片的模式，
是用來閱讀外語文件的長文翻譯、心智圖和 TTS 功能，
並支援 .txt、.md 或直接開編輯器手動貼入。

規定使用者翻譯前需要使用換行標記段落，
每 300 字就需要切分一個段落。

或是直接沿用現在的 srt 編輯器，
來調整切分段落

感謝您做了這款軟體，
真的很棒！

**Comment by Makememo** [comment]
新产品已经在开发，专注文档管理。

**Comment by Makememo** [comment]
https://pemo.ai/ 后续此产品将用于文档管理以及浏览。
