### ISSUE TITLE
openai调取不成功

### ISSUE THREAD

**Issue by pokemon15139** [Makememo/MemoAI#258]
**Describe the bug**
openai调取不成功，一直显示翻译中。进入opnenai后台，api并无问题。m1max mac sonoma
**To Re
<img width="890" alt="截屏2024-04-16 11 36 58" src="https://github.com/Makememo/MemoAI/assets/104640739/243a547e-42b3-4531-924e-63b849f972d7">

produce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 14]
 - Model[e.g. Large]
 - Version [e.g. 1.1.2]

**Additional context**

**Comment by pokemon15139** [comment]
<img width="856" alt="截屏2024-04-16 13 44 29" src="https://github.com/Makememo/MemoAI/assets/104640739/393070f4-7ddb-4883-9b1a-1fa1d7dbd97e">

**Comment by Makememo** [comment]
现在 Open AI 要充值，以及特定地域才能用。
