### ISSUE TITLE
每次重啟都需要邀請碼,

### ISSUE THREAD

**Issue by xiaotsai** [Makememo/MemoAI#26]
每次重啟都需要邀請碼,導致同個邀請碼達到上限,無法再登入
![image](https://github.com/Makememo/MemoAI/assets/49838210/83698d21-15c0-4104-9a0e-2db929e58b19)

**Comment by xiaotsai** [comment]
剛剛沒打完不知道怎麼突然就發出去了

**Comment by Makememo** [comment]
OK，我们解决一下，方便告知一下邮箱么？我们给你解除限制。

**Comment by xiaotsai** [comment]
joejoetsai0502@gmail.com

**Comment by Makememo** [comment]
反激活了，你重新输入然后点击一次看看。

**Comment by xiaotsai** [comment]
可以了 但是只要我關掉又重開還是需要重新輸入, 期待你們修復這個問題。 或是有個license 管理之類的

**Comment by Makememo** [comment]
那很奇怪，方便的发在设置 - 实验室导出日志发给我，我们排查一下。

**Comment by xiaotsai** [comment]
[export_log.zip](https://github.com/Makememo/MemoAI/files/12728435/export_log.zip)

**Comment by Makememo** [comment]
升级到 1.0.8 看看是否还有此类情况。
