### ISSUE TITLE
中文字幕一直是繁体，我想修改下prompt但没找地方呢？

### ISSUE THREAD

**Issue by foreverzmj** [Makememo/MemoAI#264]
中文字幕一直是繁体，我想修改下prompt但没找地方呢？

**Comment by Makememo** [comment]
你转写时候选了 auto 还是简体中文？

**Comment by Makememo** [comment]
能否录制一个视频？语言选择简体中文我们是有强制过滤措施。

**Comment by foreverzmj** [comment]
https://github.com/Makememo/MemoAI/assets/43919382/957778a4-f126-422a-af0a-464cc29d4162

**Comment by foreverzmj** [comment]
知道了，导入视频时候要选中文，我那用的默认是自动，改成简体中文就好了。要是在后面有个地方能修改就好了，貌似一旦导入了就没地方再去看当时怎么选的了，也不能调整了
