### ISSUE TITLE
YouTube视频字幕

### ISSUE THREAD

**Issue by pure-maple** [Makememo/MemoAI#267]
YouTube视频导入时能否自动读取视频本身已有的字幕及翻译，而不是调用本地模型再次重新转写。

**Comment by pure-maple** [comment]
另，是否能够手动选择导入的视频画质，目前只有设置中能够选择质量优先或者速度优先，希望能够设置更加细化的画质选项，如1080P, 720P等。

**Comment by Makememo** [comment]
> 另，是否能够手动选择导入的视频画质，目前只有设置中能够选择质量优先或者速度优先，希望能够设置更加细化的画质选项，如1080P, 720P等。

This could be a separate issue.

**Comment by Makememo** [comment]
1.3.8 已经支持
