### ISSUE TITLE
升级的 1.3.1 打开程序报错

### ISSUE THREAD

**Issue by scomper** [Makememo/MemoAI#269]
**Describe the bug**
升级的 1.3.1 打开程序报错，点击 Memo App 无响应。

**Screenshots**
![CleanShot 2024-05-12 at 20 03 27@2x](https://github.com/Makememo/MemoAI/assets/13041847/b71f9430-e9fb-4166-81e3-c24b9dfe196a)

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 14.5 (23F79)]
 - Version [e.g. 1.3.1]

**Additional context**

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/releases/tag/v1.3.1 修复了，可以下载了。
