### ISSUE TITLE
see error:errorTypeError:e.substring is not a function

### ISSUE THREAD

**Issue by Hi-choco** [Makememo/MemoAI#270]
![屏幕截图 2024-05-13 014457](https://github.com/Makememo/MemoAI/assets/169603438/1256a944-717b-434f-8305-3f854d372c6d)
**Describe the bug**
When I edit the video, it says: errorTypeError:e.substring is not a function
**To Reproduce**
1. Go to memo
2. Click on the video
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 11
 - Model[Large v3]
 - Version [e.g. 1.3.1]

**Additional context**

**Comment by Makememo** [comment]
Upgrade to 1.3.2 and see this error https://github.com/Makememo/MemoAI/releases/tag/v1.3.2
