### ISSUE TITLE
在用TTS合成语音的时候显示错误

### ISSUE THREAD

**Issue by KIILIIG** [Makememo/MemoAI#272]
![QQ截图20240514062649](https://github.com/Makememo/MemoAI/assets/169726609/72517c3f-9d2a-4c02-ad13-246ccfa53681)

**Comment by Makememo** [comment]
删除内容中的；标点符号即可。

**Comment by KIILIIG** [comment]
> 删除内容中的；标点符号即可。

好的，非常感谢，还有一个问题想要咨询，我的内测码复制进去显示失败，不是说所有功能都可以免费试用吗，但是目前pro的功能我用不了……
