### ISSUE TITLE
gemini 翻譯異常

### ISSUE THREAD

**Issue by Rex6365** [Makememo/MemoAI#274]
![image](https://github.com/Makememo/MemoAI/assets/168889172/c0600258-b517-4eca-8063-ae44c82633db)
測試翻譯時出現"First parameter has member 'readable' that is not a ReadableStream"，請問該如何解決?

**Comment by Makememo** [comment]
應該是剛出了新版本，我們適配一下。

**Comment by danielxing** [comment]
请问什么时候可以修复好？现在还是不能用gemini翻译。。。 :(

**Comment by Makememo** [comment]
測試 Gemini 一切正常，你們是否有有重新申請 key？或者在 gemini 所要求的地區使用？

**Comment by Rex6365** [comment]
![image](https://github.com/Makememo/MemoAI/assets/168889172/3f893fbc-5956-4f88-a24e-a5a97212c5cd)
有重新申請 key，也在 gemini 所要求的地區使用，但gemini還是無法使用

**Comment by Makememo** [comment]
三方整合中先刪除 Gemini，再安裝看看是否生效。

目前這個問題我們反復測試也未曾復現。

最好設置-實驗室-導出一下日志。

**Comment by danielxing** [comment]
重装了Gemini还是不行，重新生成key还是不行。上周试过还可以，下方是报错截图和导出日志。

￼

**Comment by Rex6365** [comment]
[2024-05-25.log](https://github.com/Makememo/MemoAI/files/15443972/2024-05-25.log)

**Comment by Makememo** [comment]
[info 00:00:11.759        ]  Start Gemini translate
[info 00:00:12.053        ]  Error: [429 Too Many Requests] Resource has been exhausted (e.g. check quota).


超過額度了，可以充值一下。

**Comment by Rex6365** [comment]
[info 23:23:00.929        ]  auto get system proxy
[info 23:23:00.930        ]  表示没有配置代理
[info 23:41:32.781        ]  Start translate line
[info 23:41:32.782        ]  Start Gemini translate
[info 23:41:35.113        ]  TypeError: First parameter has member 'readable' that is not a ReadableStream.

我用另一個沒有使用過的帳戶生成key，測試翻譯還是一樣

**Comment by Makememo** [comment]
我重新发布了一个版本，请前往集成中测试用。

**Comment by Rex6365** [comment]
用最新的v1.3.2還是無法翻譯，但v1.3.0可以正常翻譯
![image](https://github.com/Makememo/MemoAI/assets/168889172/2df6779a-1734-41de-bae8-1cc4b34c538e)

**Comment by minworld** [comment]
<img width="1200" alt="image" src="https://github.com/Makememo/MemoAI/assets/43404240/4359c672-4378-42cd-b46e-da1ceb367d5b">
这边也复现了相同的问题

**Comment by minworld** [comment]
<img width="1901" alt="image" src="https://github.com/Makememo/MemoAI/assets/43404240/173cb85d-2641-4c28-8b39-db7f77a0ec62">
[export_log.zip](https://github.com/user-attachments/files/15637623/export_log.zip)
这边附上了dui y3时间点的日志，看样子和报错的一致。

**Comment by Rex6365** [comment]
@minworld v1.3.0之後的版本都有這個問題

**Comment by Makememo** [comment]
1.3.8 已经定位解决。
