### ISSUE TITLE
转写完，字幕还是会消失。

### ISSUE THREAD

**Issue by fengyunzaidushi** [Makememo/MemoAI#276]
![image](https://github.com/Makememo/MemoAI/assets/53250064/71541332-e971-4167-97eb-f44c63d47824)

**Comment by Makememo** [comment]
![image](https://github.com/Makememo/MemoAI/assets/140973261/09b351fc-ab92-431a-809d-2519575cc820)

參考這個，講所有包含 cache 字樣的文件夾刪除。

懷疑是緩存太多問題導致。

**Comment by Makememo** [comment]
![CleanShot 2024-05-18 at 19 27 32@2x](https://github.com/Makememo/MemoAI/assets/140973261/43772ced-e4f6-497a-97b1-8c6ceaec996d)
这里选错错了。
