### ISSUE TITLE
转写任务长时间不动

### ISSUE THREAD

**Issue by runningZ1** [Makememo/MemoAI#277]
转写任务长时间为0%，网络正常，模型正常，不知如何解决？
![image](https://github.com/Makememo/MemoAI/assets/127315512/127c3a3f-5227-483f-b124-f88678c41d57)
![image](https://github.com/Makememo/MemoAI/assets/127315512/ec59ca84-3d41-431a-b7ae-5bd005a0ad80)

**Comment by Makememo** [comment]
微信 memohq 给你发新的测试包看看
