### ISSUE TITLE
如何添加新模型比如阿里的通义大模型？

### ISSUE THREAD

**Issue by zgbjmy2009** [Makememo/MemoAI#278]
如何添加新模型比如阿里的通义大模型？我在里面找到百度和腾讯的了，但是没找到阿里的通义......自己添加的话怎么弄？

**Comment by RacingRaymond** [comment]
我也需要这个，最近发现通义的翻译更合我意

**Comment by Makememo** [comment]
已经支持，请前往设置 - 集成 - 刷新后下载。
