### ISSUE TITLE
长录音转文字出现大段重复文字

### ISSUE THREAD

**Issue by SilveRMO0N13** [Makememo/MemoAI#280]
**Describe the bug**
使用medium和large v1模型转录会议录音，时长超过40分钟的，出现大段重复文字而没有输出正确文字，且多次重新转录结果相同

**To Reproduce**
批量任务中添加录音文件，模型选择medium或large v1，GPU加速，录音文件超过40分钟

**Expected behavior**
正常输出录音对应的文字
**Screenshots**
![image](https://github.com/Makememo/MemoAI/assets/10579062/014b87c6-ce72-469f-a09a-6d6c438e4d18)
![image](https://github.com/Makememo/MemoAI/assets/10579062/6f6ca6c7-c86f-47e8-9b52-5852a6fafb0e)

**Desktop (please complete the following information):**
 - OS:Windows 11 23H2
 - Model: Medium/ Large V1
 - Version 1.3.2
 - Hardware AMD Ryzen 8845U with Radeon 780M

**Additional context**

**Comment by joyshan1986** [comment]
同样的问题，一个多月前已经微信反馈了，请尽快修复这个bug

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/releases/tag/v1.3.3 

- When transcribing, select cuda mode for GPU mode
- Go to Settings-Lab-Turn on the flash attention mechanism switch
--
- 轉寫時，GPU 模式選擇 cuda 模式
- 前往設置 - 實驗室 - 打開 flash attention 機制開關

查看问题教程：https://memo.ac/zh/blog/whisper-hallucinations
