### ISSUE TITLE
輸入邀請碼後，跳出錯誤訊息無法登入。

### ISSUE THREAD

**Issue by Itzachen** [Makememo/MemoAI#281]
**Describe the bug**
輸入邀請碼後，跳出錯誤訊息無法登入。

**Screenshots**
<img width="390" alt="截圖 2024-05-25 下午4 11 01" src="https://github.com/Makememo/MemoAI/assets/12710151/a21b7b0a-5c6c-4c84-8813-1dfcb511be16">

**Desktop (please complete the following information):**
 - OS: macOS 14
 - Sonoma
 - Version 14.2.1

**Comment by Makememo** [comment]
1. 檢查一下網絡 DNS 服務
2. 關閉殺毒軟件網絡防火牆
