### ISSUE TITLE
1.31 和 1.32 版本批量转写本地后无法导出

### ISSUE THREAD

**Issue by joyshan1986** [Makememo/MemoAI#282]
这两个版本转写完成后，就卡在导出环节。

我卸载了 1.31和1.32后，用回1.30又可以导出了。

另外，40分钟以上的，转写会出现问题，内容重复或者时间戳错误，我的机器64G内存，2080ti的显卡22G显存，不会存在内存不够的情况。

请Memo团队尽快解决时间长的视频出现内容重复或者时间戳错误的问题，软件的根本功能是转写，如果这个一直不解决，增加各种新功能就是无本之木。

谢谢！

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/releases/tag/v1.3.3
