### ISSUE TITLE
Unable to execute TTS generation for translated subtitles(Detected subtitle issue)

### ISSUE THREAD

**Issue by bzdk** [Makememo/MemoAI#283]
**Describe the bug**
After the translated subtitle is generated, start TTS generation, then a warning showed:

Detected subtitle issue 
[object] [object]

**Screenshots**
<img width="308" alt="Screenshot 2024-05-27 at 15 19 39" src="https://github.com/Makememo/MemoAI/assets/141992/0547ce00-0c80-45c5-94c6-ed1648af325e">

**Desktop (please complete the following information):**
 - OS: MacOS 14.4
 - Version 1.3.2

**Comment by Makememo** [comment]
Please export the log to me from the setting - lab.

Which is then sent to feedback@memo.ac

**Comment by Makememo** [comment]
Please check if any subtitle lines are empty.
