### ISSUE TITLE
无法翻译字幕文件

### ISSUE THREAD

**Issue by xbtachlb** [Makememo/MemoAI#285]
**Describe the bug**
srt格式的字幕文件，导入后无法翻译，卡在0%。翻译API测试可用。
![image](https://github.com/Makememo/MemoAI/assets/46466876/10a2a167-0857-43fb-9415-2421911b7dde)

Windows11, 1.3.3

**Comment by Makememo** [comment]
设置 - 实验室导出一下日志

**Comment by xbtachlb** [comment]
> 设置 - 实验室导出一下日志

不好意思，是因为翻译用时太久了，我误以为是卡住了，最后成功了
