### ISSUE TITLE
已經設定了Open API Key但不知為何，測試翻譯一直失敗，也無法使用總結功能

### ISSUE THREAD

**Issue by spring14013** [Makememo/MemoAI#288]

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/assets/140973261/a6c15453-564f-4e37-bc41-4ee262029680

從這裏提交一下問題，我們看看日誌。

**Comment by Makememo** [comment]
通常來說：
1. Key 沒有充錢
2. 網絡問題

**Comment by 1WorldCapture** [comment]
赞同，这个可以关掉，最新版本我测试了没问题
