### ISSUE TITLE
Transcription Error

### ISSUE THREAD

**Issue by fengtalk** [Makememo/MemoAI#290]
**Describe the bug**

**To Reproduce**
转写时，出现以下提示：

```
Transcription Error
A dynamic link library(DLL) initialization routine
failed. \\?
\
C:\Users\fengtalk\AppData\Local\Programs\Memo\resources\addon\whisper-addon.node
```

**Expected behavior**

**Screenshots**

![cf9dffe52fa15d23a288c14e77bea53](https://github.com/Makememo/MemoAI/assets/2913058/0ec97438-ae22-4035-8c3c-a15eb20da63a)

**Desktop (please complete the following information):**
 - OS: [Windows 11]

**Additional context**

Memo Version: v1.3.5

**Comment by Makememo** [comment]
应用内左下角帮助与反馈提交一下问题，会同步日志给我。

**Comment by Makememo** [comment]
Windows ARM 芯片么？这个当下不支持。 目前手头并无此类设备，等使用人数上来后再支持。
