### ISSUE TITLE
windows 10启动转写失败，提示错误：The specified module could not be found

### ISSUE THREAD

**Issue by herainwang** [Makememo/MemoAI#294]
**Describe the bug**
安装完以后启动转写就失败，Log如下：
[info 19:34:02.016 (error)]  ----------------------------- application starting [2024-07-10-07-34-02] ---------------------------------------
[info 19:34:02.098        ]  -----------install local plugins
[info 19:34:02.100        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-translate-claude@1.0.3.memox
[error 19:34:02.103        ]  (node:10908) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `Memo --trace-deprecation ...` to show where the warning was created)
[info 19:34:02.159        ]  memo-plugin-translate-claude 1.0.3
[info 19:34:02.160        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-translate-deepl@1.0.2.memox
[info 19:34:02.207        ]  memo-plugin-translate-deepl 1.0.2
[info 19:34:02.208        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-translate-google@1.0.4.memox
[info 19:34:02.235        ]  memo-plugin-translate-google 1.0.4
[info 19:34:02.236        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-translate-microsoft@1.0.3.memox
[info 19:34:02.274        ]  memo-plugin-translate-microsoft 1.0.3
[info 19:34:02.275        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-translate-ollama@1.0.3.memox
[info 19:34:02.315        ]  memo-plugin-translate-ollama 1.0.3
[info 19:34:02.316        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-translate-openai@1.0.8.memox
[info 19:34:02.350        ]  memo-plugin-translate-openai 1.0.8
[info 19:34:02.351        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-tts-edge@1.0.1.memox
[info 19:34:02.381        ]  memo-plugin-tts-edge 1.0.1
[info 19:34:02.382        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-tts-elevenlabs@1.0.3.memox
[info 19:34:02.416        ]  memo-plugin-tts-elevenlabs 1.0.3
[info 19:34:02.417        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-tts-openai@1.0.1.memox
[info 19:34:02.448        ]  memo-plugin-tts-openai 1.0.1
[info 19:34:02.449        ]  -----------finished
[info 19:34:02.452        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\addon\cublas\whisper-addon.node --> C:\Users\huawei\.memo-ai\addon\whisper\win32\x64\cublas
[info 19:34:02.454        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-translate-claude@1.0.3.memox removed successfully
[info 19:34:02.455        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-translate-deepl@1.0.2.memox removed successfully
[info 19:34:02.455        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-translate-google@1.0.4.memox removed successfully
[info 19:34:02.456        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-translate-microsoft@1.0.3.memox removed successfully
[info 19:34:02.456        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-translate-ollama@1.0.3.memox removed successfully
[info 19:34:02.457        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-translate-openai@1.0.8.memox removed successfully
[info 19:34:02.458        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-tts-edge@1.0.1.memox removed successfully
[info 19:34:02.458        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-tts-elevenlabs@1.0.3.memox removed successfully
[info 19:34:02.459        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\plugins\memo-plugin-tts-openai@1.0.1.memox removed successfully
[info 19:34:02.487        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\locales\de.json
[info 19:34:02.491        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\addon\cublas\whisper.dll --> C:\Users\huawei\.memo-ai\addon\whisper\win32\x64\cublas
[info 19:34:02.507        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\locales\en.json
[info 19:34:02.524        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\locales\es.json
[info 19:34:02.541        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\locales\it.json
[info 19:34:02.555        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\locales\ja.json
[info 19:34:02.594        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\locales\ko.json
[info 19:34:02.610        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\addon\cublas\whisper.dll removed successfully
[info 19:34:02.611        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\addon\cublas\whisper-addon.node removed successfully
[info 19:34:02.614        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\locales\zh-CN.json
[info 19:34:02.627        ]  C:\Users\huawei\AppData\Local\Programs\Memo\resources\locales\zh-TW.json
[info 19:34:02.875        ]  init db table
[info 19:34:03.086        ]  auto get system proxy
[info 19:34:03.089        ]  read local plugins
[info 19:34:03.123        ]  
-----------------------installedPlugins-------------------------
tts     memo-plugin-tts-openai
tts     memo-plugin-tts-elevenlabs
tts     memo-plugin-tts-edge
translate     memo-plugin-translate-openai
translate     memo-plugin-translate-ollama
translate     memo-plugin-translate-microsoft
translate     memo-plugin-translate-google
translate     memo-plugin-translate-deepl
translate     memo-plugin-translate-claude
---------------------------------------------------------------

[info 19:34:03.124        ]  filePath undefined
[info 19:34:03.279        ]  表示没有配置代理
[info 19:34:03.295        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\locales\de.json removed successfully
[info 19:34:03.295        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\locales\en.json removed successfully
[info 19:34:03.296        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\locales\it.json removed successfully
[info 19:34:03.297        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\locales\es.json removed successfully
[info 19:34:03.298        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\locales\ja.json removed successfully
[info 19:34:03.298        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\locales\zh-CN.json removed successfully
[info 19:34:03.299        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\locales\zh-TW.json removed successfully
[info 19:34:03.300        ]  remove: C:\Users\huawei\AppData\Local\Programs\Memo\resources\locales\ko.json removed successfully
[info 19:34:03.300        ]  note table exist
[info 19:34:03.306        ]  download table exist
[info 19:34:03.312        ]  workspace table exist
[info 19:34:03.313        ]  folder table exist
[info 19:34:03.315        ]  resource table exist
[info 19:34:03.317        ]  doc table exist
[info 19:34:03.318        ]  tag table exist
[info 19:34:03.320        ]  note_tag table exist
[info 19:34:03.322        ]  doc_tag table exist
[info 19:34:03.323        ]  migrate latest
[info 19:34:03.339        ]  migrate latest end
[info 19:34:04.545        ]  get online plugins
[error 19:34:06.958        ]  nvcc --version error: Command failed: nvcc --version
'nvcc' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

[error 19:34:07.893        ]  nvidia-smi error: Command failed: nvidia-smi
'nvidia-smi' �����ڲ����ⲿ���Ҳ���ǿ����еĳ���
���������ļ���

[info 19:34:07.996        ]  checking for updates
[info 19:34:07.997        ]  Checking for update
[info 19:34:07.998        ]  autoUpdater start checking for update
[info 19:34:08.662        ]  Setting changed msg
[info 19:34:08.693        ]  undefined
[info 19:34:10.676        ]  
===========================================================================================
  System Information    Windows 10.0.19045 x64
  Memo Version          v1.3.5
===========================================================================================
  CPU             |  Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8core)
  GPU             |  Intel(R) UHD Graphics 1024MB
                  |  Virtual Display Device
-------------------------------------------------------------------------------------------
  Total Memory    |  15.839252471923828 GB
  Free Memory     |  9.682563781738281 GB
-------------------------------------------------------------------------------------------
  Screen          |  Huaqin PnP Monitor\\.\DISPLAY1 (main display) 3000x2000 59
-------------------------------------------------------------------------------------------
  
[info 19:34:12.651        ]  Update for version 1.3.5 is not available (latest version: 1.3.5, downgrade is disallowed).
[info 19:34:12.652        ]  update not available { update: false, version: '1.3.5', newVersion: '1.3.5' }
[info 19:34:58.560        ]  Start transcription: 测试录音.m4a {
  transcriptType: 'local',
  model: 'ggml-tiny.bin',
  language: 'zh_s',
  prompt: '',
  translateLanguage: 0,
  mergeAudio: 0,
  maxLen: 150,
  enableMaxLen: false,
  enableAutoLen: false
}
[info 19:34:58.561        ]  start vad:  C:\Users\huawei\AppData\Roaming\Memo\temp\memo\de7920a1-3fe5-4c6f-98a0-0fa0255d94a0\276656bc-aa13-4a2d-9cd4-e6aea8fcb8f3.wav
[error 19:34:58.702        ]  Run Whisper Error Error: The specified module could not be found.
\\?\C:\Users\huawei\AppData\Local\Programs\Memo\resources\addon\vad\vad_addon.node
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2107)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2107)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/node_init:2:13357)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (C:\Users\huawei\AppData\Local\Programs\Memo\resources\app.asar\node_modules\bytenode\lib\index.js:306:23)
    at Ezr (evalmachine.<anonymous>:1:2547432)
    at R5t (evalmachine.<anonymous>:1:2547696)
[error 19:34:58.768        ]  Run Whisper Error Error: The specified module could not be found.
\\?\C:\Users\huawei\AppData\Local\Programs\Memo\resources\addon\whisper-addon.node
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2107)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2107)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/node_init:2:13357)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (C:\Users\huawei\AppData\Local\Programs\Memo\resources\app.asar\node_modules\bytenode\lib\index.js:306:23)
    at cPe (evalmachine.<anonymous>:1:2524542)
    at VBr (evalmachine.<anonymous>:1:2526105)
[error 19:34:58.769        ]  Error occurred in handler for 'start-transcribe': Error: The specified module could not be found.
\\?\C:\Users\huawei\AppData\Local\Programs\Memo\resources\addon\whisper-addon.node
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2107)
    at Object.<anonymous> (node:internal/modules/cjs/loader:1356:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2107)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/node_init:2:13357)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (C:\Users\huawei\AppData\Local\Programs\Memo\resources\app.asar\node_modules\bytenode\lib\index.js:306:23)
    at cPe (evalmachine.<anonymous>:1:2524542)
    at VBr (evalmachine.<anonymous>:1:2526105)

**To Reproduce**
重复多次，每次都不行

**Screenshots**
![Uploading 屏幕截图(3).png…]()

**Comment by Makememo** [comment]
感觉上是安装问题，不知道当时如何安装了 Memo，升级了 1.3.8 是否正常。

**Comment by Makememo** [comment]
360 之类的杀毒软件清理掉了 Memo 的依赖，可以去隔离区给 Memo 开个白名单。
