### ISSUE TITLE
支持阿里巴巴最近开源的SenseVoice small也许会更好？

### ISSUE THREAD

**Issue by Diplproveably** [Makememo/MemoAI#295]
最近试着运行了阿里巴巴最近开源的SenseVoice small, 速度很快，效果虽然很难说到底有没有whisper large好，但是绝对比medium好得多。速度也至少比whisper large 快五倍（在4070上）。
不过我没有找到怎么让SenseVoice 输出字幕😂，我甚至怀疑这个模型根本不支持输出字幕，也有可能是我太笨了没有完全理解文档😂

**Comment by Makememo** [comment]
SenseVoice small 测试下来不符合我们标准。
