### ISSUE TITLE
批量处理任务

### ISSUE THREAD

**Issue by guochao00** [Makememo/MemoAI#297]
1.3.6版本里面我见有批量模式，可以批量处理任务，但是在哪里实现呢，我多选视频也放不进软件里面啊？
![无标题](https://github.com/user-attachments/assets/357cc343-a7fd-4005-95c4-d3593a311e52)

**Comment by 1WorldCapture** [comment]
+1

**Comment by Makememo** [comment]
开通 Pro 后，点击 Personal 旁边 +

**Comment by 1WorldCapture** [comment]
> 开通 Pro 后，点击 Personal 旁边 +

Bingo
