### ISSUE TITLE
Error: context_ length_exceeded 

### ISSUE THREAD

**Issue by WingCH** [Makememo/MemoAI#3]
字幕太多時用OpenAI 翻譯會出現 `context_ length_exceeded`
![a](https://github.com/Makememo/MemoAI/assets/19588517/c778ae88-b43a-46b7-9063-7dd76d400acf)

**Comment by Makememo** [comment]
Hi～这个是 Open AI 返回的错误，原因是一次性输入的 Token 数量过多，后续我们会加上分段翻译来解决。
