### ISSUE TITLE
字幕以markdown导出时，没有短句，希望能够导出有断句的功能，即使是每行字幕之间只是逗号都可以，谢谢！

### ISSUE THREAD

**Issue by ZhuowenJ** [Makememo/MemoAI#30]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Makememo** [comment]
导出是英文还是中文？

**Comment by ZhuowenJ** [comment]
导出是中文的

**Comment by Makememo** [comment]
转写时候可以填写提示词：“请添加标点符号。”
