### ISSUE TITLE
在导入本地媒体时，出现了报错

### ISSUE THREAD

**Issue by Muxin33** [Makememo/MemoAI#300]
![15000897_42de2c03-a7b3-4849-efe5-bfc70fd500fe](https://github.com/user-attachments/assets/b4537d28-ec69-432d-8817-24d987aa7feb)

**Comment by Makememo** [comment]
設置-實驗室-導出一下日誌發給我哈。

**Comment by Muxin33** [comment]
[Uploading 2024-08-07.log…]()
[Uploading 2024-08-08.log…]()

**Comment by Muxin33** [comment]
[export_log.zip](https://github.com/user-attachments/files/16538337/export_log.zip)

**Comment by Muxin33** [comment]
刚才又试了一下，导入本地视频有没事儿了...
