### ISSUE TITLE
在連結放入 Apple Podcast 連結，一直出現「獲取媒體信息失敗」

### ISSUE THREAD

**Issue by MarsTsraM** [Makememo/MemoAI#307]
**Describe the bug**
在連結放入 Apple Podcast 連結，一直出現「獲取媒體信息失敗」

**To Reproduce**
![image](https://github.com/user-attachments/assets/e41b71ef-6cca-4450-b416-900c8c5e78a1)
![image](https://github.com/user-attachments/assets/b9cee4b4-c60b-4ce9-9d80-fbd6281a7c8e)

3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**
可以轉寫，或是可以告訴我要怎麼填入連結。

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 14]
 - Model[e.g. Large]
 - Version [e.g. 1.1.2]

**Additional context**

**Comment by MarsTsraM** [comment]
https://podcasts.apple.com/tw/podcast/ep68-%E5%A6%82%E4%BD%95%E5%9C%A8%E9%80%86%E5%A2%83%E4%B8%AD%E4%BF%9D%E6%9C%89%E5%88%9D%E8%A1%B7-%E5%89%B5%E9%80%A0%E5%80%8B%E4%BA%BA%E5%93%81%E7%89%8C%E7%9A%84%E5%BD%B1%E9%9F%BF%E5%8A%9B-ft-%E9%98%BF%E9%87%91-%E4%BA%BA%E7%94%9F%E9%80%B2%E5%8C%96%E4%B8%AD-%E5%89%B5%E8%BE%A6%E4%BA%BAkim/id1682939097?i=1000666177304

**Comment by Makememo** [comment]
下个版本解决

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/releases/tag/v1.3.9
