### ISSUE TITLE
字幕前台显示

### ISSUE THREAD

**Issue by eatgrass** [Makememo/MemoAI#31]
**Is your feature request related to a problem? Please describe.**
我经常会在工作或电脑前做其他事情的时候一边听一些英文播客，有时候碰到没听明白的就会去看看字幕，于是我就不得不把memo切到前台，再倒回到没听清的地方
**Describe the solution you'd like**
希望能做一个前台字幕显示的功能，类似一些音乐播放器的前台歌词显示那样，可以Pin在前台

**Describe alternatives you've considered**

**Additional context**

**Comment by Makememo** [comment]
后续迭代会支持，结合实时语音识别一起。
