### ISSUE TITLE
上傳長音檔，無法轉出文字

### ISSUE THREAD

**Issue by miyabizhan** [Makememo/MemoAI#310]
**Describe the bug**
上傳18分鐘的音檔(格式 m4a)，無法轉出文字

**To Reproduce**
1. Go to 'memo 首頁'
2. Click on '選擇本地媒體'
3. 上傳音檔(格式 m4a)
4. 設定格式
<img width="509" alt="image" src="https://github.com/user-attachments/assets/0003142e-d877-4ec2-9a6e-16ee48788503">

5. 點擊"轉寫"
6. See error 無法轉出文字 
<img width="986" alt="image" src="https://github.com/user-attachments/assets/5518621a-ba06-42e0-9641-333b5315c457">

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 -  macOS 14.3.1（23D60）
 - Model[ small ]
 - Version [1.3.8]

**Comment by Makememo** [comment]
關閉人聲檢測是否正常？

**Comment by Makememo** [comment]
後續遇到問題還可以查看這裡： https://memo.ac/zh_tw/blog/whisper-hallucinations

**Comment by miyabizhan** [comment]
hi

收到，問題已排除，謝謝你們有效率的回覆！

miyabi

Memo AI ***@***.***> 於 2024年9月22日 週日 下午6:40寫道：
