### ISSUE TITLE
whisper-large-v3-turbo

### ISSUE THREAD

**Issue by amorist** [Makememo/MemoAI#315]
Whisper large-v3-turbo is a finetuned version of a pruned [Whisper large-v3](https://huggingface.co/openai/whisper-large-v3). In other words, it's the exact same model, except that the number of decoding layers have reduced from 32 to 4. As a result, the model is way faster, at the expense of a minor quality degradation.

**Comment by Makememo** [comment]
![image](https://github.com/user-attachments/assets/e666c320-52c4-4cc6-923f-6243036bb9fb)
![image](https://github.com/user-attachments/assets/034d69c4-a415-46d7-9a13-7ff18fb8b052)
