### ISSUE TITLE
各位千万不要开pro 

### ISSUE THREAD

**Issue by FrankHepi** [Makememo/MemoAI#317]
首先，我不排斥收费
要是模型在云端，这钱你该收
搞笑的是用户用本地端转写，需要开pro才能用，用的模型还是开源的模型
合着用户承担算力成本，开源项目承担研发成本，自个做个集合就收费，把用户当🤡呗

各位可以自己部署whisperx
```
whisperx test.mp4 --device cuda --output_format srt --language en --vad_onset 0
.5 --vad_offset 0.35 --chunk_size 10 --no_speech_threshold 0.3
```
用这个参数，转写断句和他的差不多，然后倒入再进行翻译，开这个pro永久要99刀还只能在3个设备上用，谁开谁🤡

**Comment by FrankHepi** [comment]
gpu加速也要收费，绝了👍

**Comment by FrankHepi** [comment]
贵司再好好的处理一下收费标准吧，把用户当傻子活不久的

**Comment by Makememo** [comment]
开源确实有很多，但不是所有人都会代码部署。

Memo 开发需要持续维护，收费是为了更久地做下去，解决一些无代码能力人群无法解决的问题。

你完全可以按照你的方式自己宣传推广免费，而不是在这里用这种方式评论。

**Comment by FrankHepi** [comment]
> 开源确实有很多，但不是所有人都会代码部署。
> 
> Memo 开发需要持续维护，收费是为了更久地做下去，解决一些无代码能力人群无法解决的问题。
> 
> 你完全可以按照你的方式自己宣传推广免费，而不是在这里用这种方式评论。

首先我没有排斥收费，而是你们的收费逻辑就有问题，凭什么在本地端运行的方式要用户收费，特别像是gpu加速，你这是骗傻子，我也说的很明白了“用户承担算力成本”却还需要付费才能使用，所以我诉求的是合理的收费标准

**Comment by Makememo** [comment]
如果你是程序员，我相信你会尊重一下自己的劳动。

Memo 做的是一体解决方案，按照你的逻辑，咨询专家动动嘴就能拿上千上万一场，他们的方案书籍，网络上都有。大家不应该看书吗？

我以前和你一样，觉得软件免费是应该的。当我自己踏足自己做产品，背后并非如此。实际上软件背后是客户服务支撑，代码工作比重并不大。

还有营销投入等等...

很感谢开源缩短了我们解决方案的打磨时间，免费始终只是一种营销方式，想要维护的够久，只能收费。

**Comment by Makememo** [comment]
> > 开源确实有很多，但不是所有人都会代码部署。
> 
> > 
> 
> > Memo 开发需要持续维护，收费是为了更久地做下去，解决一些无代码能力人群无法解决的问题。
> 
> > 
> 
> > 你完全可以按照你的方式自己宣传推广免费，而不是在这里用这种方式评论。
> 
> 
> 
> 首先我没有排斥收费，而是你们的收费逻辑就有问题，凭什么在本地端运行的方式要用户收费，特别像是gpu加速，你这是骗傻子，我也说的很明白了“用户承担算力成本”却还需要付费才能使用
> 
> 所以我诉求的是合理的收费标准

所以翻译功能都是免费使用，我们没做任何限制。

大部分人用均衡模型就能获取很好的效果。以及不要辱骂，你可以质疑不合理，但是辱骂是不好的行为。

**Comment by Makememo** [comment]
> > 开源确实有很多，但不是所有人都会代码部署。
> 
> > 
> 
> > Memo 开发需要持续维护，收费是为了更久地做下去，解决一些无代码能力人群无法解决的问题。
> 
> > 
> 
> > 你完全可以按照你的方式自己宣传推广免费，而不是在这里用这种方式评论。
> 
> 
> 
> 首先我没有排斥收费，而是你们的收费逻辑就有问题，凭什么在本地端运行的方式要用户收费，特别像是gpu加速，你这是骗傻子，我也说的很明白了“用户承担算力成本”却还需要付费才能使用
> 
> 所以我诉求的是合理的收费标准

以及 Memo 辐射客群是海外用户，现在 80% 注册来源都是海外。99 美金对他们来说价格只是一顿普通饭钱，几杯咖啡。

你的建议我们会考虑，但是也请不要用如此情绪来对待我们，我们不接受你这种谩骂。

**Comment by FrankHepi** [comment]
> Memo 做的是一体解决方案，按照你的逻辑，咨询专家动动嘴就能拿上千上万一场，他们的方案书籍，网络上都有。大家不应该看书吗？

我诉求的是合理的收费标准，而你们的收费逻辑有问题，我不知道为什么你一直在曲解我的意思，开头也说了我不排斥收费

但这种把成本转移到用户身上就对吗？你可以把字幕编辑功能收费，可以把压制更高码率的视频功能收费，但你们把本该就由用户自己转写的功能收费，很不合理

**Comment by FrankHepi** [comment]
> 你的建议我们会考虑，但是也请不要用如此情绪来对待我们，我们不接受你这种谩骂。

这个确实是我的不对，只是看不惯这种拿开源收费的行为

**Comment by Makememo** [comment]
> 
> 
> > Memo 做的是一体解决方案，按照你的逻辑，咨询专家动动嘴就能拿上千上万一场，他们的方案书籍，网络上都有。大家不应该看书吗？
> 
> 
> 
> 我诉求的是合理的收费标准，而你们的收费逻辑有问题，我不知道为什么你一直在曲解我的意思，开头也说了我不排斥收费
> 
> 
> 
> 但这种把成本转移到用户身上就对吗？你可以把字幕编辑功能收费，可以把压制更高码率的视频功能收费，但你们把本该就由用户自己转写的功能收费，很不合理

这个我们后续会优化，你可以继续使用开源方案导入 Memo 翻译。

但是你这种评论行为并不太好，希望你遇到其他类似产品可以合理表达你的诉求，而不是采用辱骂方式。

**Comment by Makememo** [comment]
> > 你的建议我们会考虑，但是也请不要用如此情绪来对待我们，我们不接受你这种谩骂。
> 
> 
> 
> 这个确实是我的不对，只是看不惯这种拿开源收费的行为

收费是为了更好地维护，开源断更的例子很多了。大家需要稳定的解决方案，免费只是很小的因素。

如果我们足够大，还可以利用资金反哺开源。

**Comment by FrankHepi** [comment]
> 收费是为了更好地维护，开源断更的例子很多了。大家需要稳定的解决方案，免费只是很小的因素。

我不排斥收费，而你一直以“收费是为了更好地维护”说辞曲解我的意思，如果你们能更改收费逻辑，很感谢，因为我使用后发现这是一款很好的软件

**Comment by FrankHepi** [comment]
> 收费是为了更好地维护，开源断更的例子很多了。大家需要稳定的解决方案，免费只是很小的因素。

我的意思只是让用户承担成本的行为很蠢，比如转写功能，用户用medium以上的模型需要收费才能使用，而运行模型本身是用户自己，你们没有提供运算服务，而你们却把这个功能当成卖点

再次，我不排斥收费

**Comment by Makememo** [comment]
> > 收费是为了更好地维护，开源断更的例子很多了。大家需要稳定的解决方案，免费只是很小的因素。
> 
> 
> 
> 我的意思只是让用户承担成本的行为很蠢，比如转写功能，用户用medium以上的模型需要收费才能使用，而运行模型本身是用户自己，你们没有提供运算服务，而你们却把这个功能当成卖点
> 
> 
> 
> 再次，我不排斥收费

这个是使用解决方案的一环，我们在过程中设计卡点能提升转化率。

如果更后置，用户并不会为 Memo 付费。

以及这里并不是单纯用户付出成本，我们也需要做好设备兼容，客服支持。
