### ISSUE TITLE
翻譯字幕時常出現「您的數據訓練截至2023年10月。」的原因？

### ISSUE THREAD

**Issue by evanhsu12** [Makememo/MemoAI#319]
影片原文是英文，使用open ai的翻譯語言模型翻譯成繁體中文，
卻在每句都出現「你訓練的數據直到2023年10月。」的句子。
如下圖
![CleanShot 2024-11-09 at 01 28 55@2x](https://github.com/user-attachments/assets/5ae3e3b5-8e37-442c-a068-2c2a0bf5d792)

有人遇過一樣的問題嗎？該如何解決？

**Comment by hunterwillin** [comment]
我也是遇到一樣問題

**Comment by Makememo** [comment]
![CleanShot 2024-11-14 at 00 49 41@2x](https://github.com/user-attachments/assets/4e001ad3-c7e6-4759-94c2-f65a9e6a7abf)
"Be sure to return only the translation results."

**Comment by evanhsu12** [comment]
解決了！非常感謝！
