### ISSUE TITLE
Provides options to modify fonts.

### ISSUE THREAD

**Issue by japen0617** [Makememo/MemoAI#323]
When exporting videos with embedded subtitles, Chinese characters may not display correctly. This is likely due to the font not supporting those characters.

It is recommended to add an option to change or select the font, so that Chinese characters can be displayed properly
please refer the picture as below

<img width="1101" alt="image" src="https://github.com/user-attachments/assets/5b4761a6-1143-4722-a199-0f160c3b7f9f">

**Comment by Makememo** [comment]
![CleanShot 2024-12-09 at 13 03 29@2x](https://github.com/user-attachments/assets/36920b4b-9e22-4561-92b1-22e01398d8e3)
请在这里设定一下字体。

**Comment by japen0617** [comment]
Hi Sirs
Thank you for your reply. I know I can change the font here, but I think the issue is that the font used for embedding doesn't match the operating system's fonts, causing the characters to not display properly after embedding. Currently, it seems that memoAI only provides English fonts, and doesn't include commonly used Chinese fonts like "New Fine Ming Body" (新細明體) or "Biao Kai Ti" (標楷體). That's probably why this problem occurs.
