### ISSUE TITLE
希望增加批量导出文本的功能！也希望增加多选字幕后将选择的字幕连起来的功能！

### ISSUE THREAD

**Issue by secondbrain-note** [Makememo/MemoAI#328]

**Comment by linmi** [comment]
前者已经支持了，需要 Pro 开启。后者选择后，有个合并按钮。
![2024-12-30 at 19 43 09@2x](https://github.com/user-attachments/assets/3118d865-7f73-47e9-b8f3-bfbf5d8c7a7d)

**Comment by Makememo** [comment]
前者已经有了，对 Pro 开启。后者可以参考这个使用合并。
![Google Chrome 2024-12-30 19 43 42](https://github.com/user-attachments/assets/c031c926-38e1-4318-9d70-f1c20fb19d16)
