### ISSUE TITLE
本地文件，没有声音

### ISSUE THREAD

**Issue by lanstonpeng** [Makememo/MemoAI#35]
**Describe the bug**
上传本地文件，播放无声

**Expected behavior**
有声音

**Screenshots**
![image](https://github.com/Makememo/MemoAI/assets/529451/4baf6a8e-917c-4fb0-b0af-ebd0f5cee2b9)

**Desktop (please complete the following information):**
 - OS: OSX 14
 - Version 10.09

**Additional context**
1. 确认开了声音，spotify正常播放音乐
2. 文件为MKV
3. 用第三方播放器（IINA）可以正常播放

**Comment by Makememo** [comment]
方便网盘打包一下文件么？我们测试一下。
