### ISSUE TITLE
AI总结框无法清空并为第二个视频总结

### ISSUE THREAD

**Issue by ruixg** [Makememo/MemoAI#38]
**Describe the bug**
我添加智谱AI的API Key后尝试为一个视频进行了AI全文总结，之后我打开另一个视频希望全文总结，总结框中依然留有上一个视频总结出的内容，并且没有地方点击清空，或是为新的视频进行总结的按钮。

**Expected behavior**
需要新上传媒体的总结框不带有上一个视频的总结内容，以为当前视频点按AI总结。
update刚尝试了一下全部退出软件再打开，总结框里清空了。

**Desktop:**
 - OS: MacOS
 - Browser: chrome
 - Version: Ventura 13

**Additional context**
对了另一个问题：我在软件内似乎一直不能用右键进行简单复制粘贴，必须用键盘快捷键。

**Comment by Makememo** [comment]
两个问题下个版本修复

**Comment by Makememo** [comment]
https://memo.ac/releases.html
