### ISSUE TITLE
更新后无法输出文字内容，一片空白

### ISSUE THREAD

**Issue by Arrosw** [Makememo/MemoAI#39]
更新后无法输出文字内容，重新装老版本就可以，但是新版本无法转文字。

**Comment by Makememo** [comment]
空间的文件夹是否设置在了中文文件目录下？

**Comment by Makememo** [comment]
https://memo.ac/releases.html

**Comment by Makememo** [comment]
辛苦发一下日志文件（设置 - 实验室 - 日志）

**Comment by vvangxs** [comment]
[info 14:41:21.715 (error)]  ----------------------------- application starting [2023-10-20-02-41-21] ---------------------------------------
[info 14:41:21.987        ]  自动获取系统代理
[info 14:41:22.012        ]  127.0.0.1 7890
[info 14:41:22.441        ]  当前模型路径：[object Object] 不存在
[error 14:41:22.443        ]  Error occurred in handler for 'get-model-list': Error: ENOENT: no such file or directory, scandir 'D:\Program\Memo\models'
    at Object.readdirSync (node:fs:1451:3)
    at t.readdirSync (node:electron/js2c/asar_bundle:2:10837)
    at mye (evalmachine.<anonymous>:1:1050273)
    at evalmachine.<anonymous>:1:1050731
    at node:electron/js2c/browser_init:2:97846
    at EventEmitter.<anonymous> (node:electron/js2c/browser_init:2:81359)
    at EventEmitter.emit (node:events:513:28)
[info 14:41:22.458        ]  Checking for update
[info 14:41:23.653        ]  Welcome, BETA user
[info 14:41:23.655        ]  Setting changed msg
[info 14:41:24.627        ]  Update for version 1.0.10 is not available (latest version: 1.0.10, downgrade is allowed).
[info 14:41:35.141        ]  Create model folder
[info 14:42:36.031        ]  select file, type:  resource
[info 14:42:39.802        ]  select file result:  [ 'D:\\1.mp4' ]
[info 14:42:39.806        ]  getMetadata: D:\1.mp4
[info 14:42:39.961        ]  Will generate e6ba0796-8cc9-447c-80ea-03c2c4b1f3a4.png
[info 14:42:40.245        ]  Screenshots taken
[info 14:42:42.124        ]  Start processing audio: ffmpeg -i D:\1.mp4 -y -ar 16000 -ac 1 -c:a pcm_s16le C:\Users\王大拿\AppData\Roaming\Memo\temp\e6ba0796-8cc9-447c-80ea-03c2c4b1f3a4.wav
[info 14:42:42.447        ]  Transcoding audio: 99.9987868641652% done
[info 14:42:42.451        ]  Conversion Done
[info 14:42:42.458        ]  Start transcript: 1.mp4 {
  transcriptType: 'local',
  model: 'ggml-medium.bin',
  language: 'en',
  prompt: '',
  translateLanguage: 0,
  mergeAudio: 0,
  maxLen: 150,
  autoLen: 75,
  enableMaxLen: false,
  enableAutoLength: false
}
[info 14:42:42.469        ]  {
  language: 'en',
  model: 'D:\\Program\\Memo\\models\\ggml-medium.bin',
  fname_inp: 'C:\\Users\\王大拿\\AppData\\Roaming\\Memo\\temp\\e6ba0796-8cc9-447c-80ea-03c2c4b1f3a4.wav',
  prompt: ''
}
[info 14:42:45.219        ]  transcript abort success
[info 14:42:45.220        ]  end
[info 14:42:57.139        ]  export logs: C:\Users\王大拿\Desktop\export_log.zip

**Comment by Makememo** [comment]
@vvangxs ffmpeg -i D:\1.mp4 -y -ar 16000 -ac 1 -c:a pcm_s16le C:\Users\王大拿\AppData\Roaming\Memo\temp\e6ba0796-8cc9-447c-80ea-03c2c4b1f3a4.wav

名字是中文导致，确定是 1.0.10 么？应该会提示新建空间。

**Comment by vvangxs** [comment]
版本是1.0.10。我将空间创在不含中文字符的目录，这个中文字符所在目录为缓存目录，我好像没法更改

**Comment by Makememo** [comment]
建议将 Memo 安装在非 C 盘看看，中文路径问题我们下个版本试试解决。

**Comment by vvangxs** [comment]
确实安装在非C盘，但是缓存目录默认在C盘。

**Comment by Makememo** [comment]
估计是要改 c 盘用户名，用批量版本是否还有问题？

**Comment by vvangxs** [comment]
等一手下个版本
