### ISSUE TITLE
获取媒体信息失败

### ISSUE THREAD

**Issue by chllei** [Makememo/MemoAI#40]
您好，我觉得这是一个视频笔记利器，但我这儿一直显示获取媒体信息失败，无论是 YouTube，Bilibili，还是 Coursera，Ted，deeplearning.ai，都无法获取媒体信息。

Clash 配置正常，Memo 的设置里已切换到系统代理，Memo 的设置里测试谷歌翻译正常，但就是无法获取媒体信息。请问有什么解决办法吗？

另外，能否考虑支持多一些视频源？比如寇享学术、网易公开课、各种云课堂之类的

**Comment by Makememo** [comment]
设置 - 实验室 - 导出一下日志看看哈。一般是代理问题。
