### ISSUE TITLE
字幕时间错乱

### ISSUE THREAD

**Issue by upjqq** [Makememo/MemoAI#43]
![image](https://github.com/Makememo/MemoAI/assets/132379653/1c8cf8d7-bce8-43a8-9251-751a8327cd6e)
**设备信息：**
处理器	Intel(R) Core(TM) i9-7920X CPU @ 2.90GHz   2.90 GHz
机带 RAM	96.0 GB (95.7 GB 可用)
系统类型	64 位操作系统, 基于 x64 的处理器
显卡    GTX 1080
版本	Windows 10 专业版
版本号	22H2
**Memo 版本:**
 v1.0.10
模型：Large(v2)
启用了GPU和自动断句，输入了提示词

尝试第二次转换也在相同的位置出现时间错乱（44：46之后）。将视频分成两段后解决了这个问题。

**Comment by Makememo** [comment]
能否提供更详细的信息：
- 设备信息
- Memo 版本
- 当时的操作菜单，选择了什么模型，是否打开 GPU

**Comment by Makememo** [comment]
已经修复。
