### ISSUE TITLE
视频位置重定位

### ISSUE THREAD

**Issue by MediCoderHZ** [Makememo/MemoAI#44]
非常感谢你们开发出如此优秀的软件。我希望能增加视频位置重定位功能，也就是说，当本地视频位置改变后，在Memo中再次打开该视频时，可以重新选择该视频位置当前的位置以继续播放，而不仅仅显示“视频文件不存在”。谢谢！

**Comment by Makememo** [comment]
好，我们优化一下。

**Comment by Makememo** [comment]
已经支持
