### ISSUE TITLE
AI：智谱AI的总结出现相同内容

### ISSUE THREAD

**Issue by ruhuang2001** [Makememo/MemoAI#46]
**Describe the bug**
使用智普AI总结内容出现相同的文字，目前只是在测试YouTube视频中发现，不确定本地上传是否出现

**To Reproduce**
1.传入YouTube链接
2.使用智普AI总结（中文或者英文）

**Expected behavior**
只显示一次内容

**Screenshots**
![image](https://github.com/Makememo/MemoAI/assets/36697407/95b726b8-8fe5-44e8-bfc0-b9fd51ef2716)
![image](https://github.com/Makememo/MemoAI/assets/36697407/2be67510-5379-4752-8e0a-1ec71fdc865c)

**Desktop (please complete the following information):**
 - OS: [Windows]

**Comment by Makememo** [comment]
下个版本修复。

**Comment by Makememo** [comment]
https://memo.ac/releases 修复了，感谢。
