### ISSUE TITLE
Notion导出双语文本只显示英文

### ISSUE THREAD

**Issue by ruhuang2001** [Makememo/MemoAI#47]
**Describe the bug**
无论选择导出什么语言到Notion都只有英文，导出txt和md的正常

**To Reproduce**
1. 选择导出文本
2. 选择双语/翻译语言导出到Notion

**Expected behavior**
正确导出双语/翻译语言到Notion

**Screenshots**
![image](https://github.com/Makememo/MemoAI/assets/36697407/e59a84b6-1224-4037-904c-1b7853a81932)
![image](https://github.com/Makememo/MemoAI/assets/36697407/6b09ad64-5196-4c51-9324-74d1d500acba)

**Desktop (please complete the following information):**
 - OS: [Windows]

**Comment by Makememo** [comment]
确实，我们改进改进

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/releases/tag/v1.3.1
