### ISSUE TITLE
播放时进行操作会导致功能失效

### ISSUE THREAD

**Issue by shiwangyan** [Makememo/MemoAI#49]
**Describe the bug**
在这个页面，如果在播放时对字幕框进行操作，比如拖动，调整两边长度等，会导致功能失效，例如无法保存，无法暂停等
![image](https://github.com/Makememo/MemoAI/assets/60057517/ecdca2d2-8e00-4ae7-8065-1ceeb7262d0c)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version v1.0.10

**Comment by Makememo** [comment]
收到，后续会完整改进

**Comment by Makememo** [comment]
已经改进，可以前往更新 1.1.9
