### ISSUE TITLE
设置默认翻译语言

### ISSUE THREAD

**Issue by MediCoderHZ** [Makememo/MemoAI#50]
非常感谢开发者开发这么好的软件。我在使用过程中有一点小小的建议，希望能够增加设置默认翻译语言的功能。使用场景是对单句进行翻译的时候，不用每次都要点击两次（1. 翻译；2. 简体中文）。如果能够设置默认翻译语言，只需要点击一次翻译就能够翻译为简体中文。
![CleanShot 2023-10-26 at 07 56 48](https://github.com/Makememo/MemoAI/assets/144652988/087d3d35-9e36-40ee-89f4-9d2f71b5f264)

**Comment by Makememo** [comment]
收到，后续优化一下。

**Comment by Makememo** [comment]
已经优化。
