### ISSUE TITLE
Medium size model (English Only) generates random timeline, and no subtitle in the player

### ISSUE THREAD

**Issue by yiqiaowang-arch** [Makememo/MemoAI#52]
**Describe the bug**
As described in the title, Memo AI v1.0.10 behaves unexpected after creating subtitle for a 90-min long video.
- Random timeline after 44:00 (e.g., after a sentence at 45:12, the next one has a timestamp of 00:34, see screenshot and srt example)
- no subtitle appeared in the player after 45:12.
- In the output .srt file, the timestamp is again weird (end time < start time):
SRT file example:
```[srt]
393
00:44:39,220 --> 00:44:43,720
 cost potentials we have already set but also production patterns.

394
00:44:44,000 --> 00:00:03,430
 You see something like this here for the Swiss rivers.

395
00:44:48,000 --> 00:00:10,630
 Technical operational constraints like ramping rates and so, and policy and taxes.
```

**To Reproduce**

1. Video with clear human voice in English uploaded
2. Prompt: This is a lecture in Energy System Analysis course in ETH Zurich, specifically, a lecture about bottom-up energy optimization. 
3. video playing while Memo AI transcribing

**Expected behavior**
All subtitles should be in order and the next sentence should always have a timestamp later than the previous sentence.

**Screenshots**
![image](https://github.com/Makememo/MemoAI/assets/28997207/f1b524cd-fed2-4140-b65a-e3f6d7a5b049)

**Environment:**
 - OS: Windows 11 Pro
 - Memo AI v1.0.10
 - GPU enabled (RTX 3060 Laptop, memory=6GB)

**Comment by Makememo** [comment]
Thank you for your feedback. We will check the problem and fix it in the next version.

**Comment by yiqiaowang-arch** [comment]
**Update:** after regenerating using prompt:
*This is a lecture in Energy System Analysis course about bottom-up energy optimization. Each identification waits for the discussion to end instead of breaking in the middle.*
The timeline issue disappears.

**Comment by Makememo** [comment]
> **Update:** after regenerating using prompt:
> 
> *This is a lecture in Energy System Analysis course about bottom-up energy optimization. Each identification waits for the discussion to end instead of breaking in the middle.*
> 
> The timeline issue disappears.

Can you share the original video with us? Let's find this problem.

**Comment by yiqiaowang-arch** [comment]
> > **Update:** after regenerating using prompt:
> > _This is a lecture in Energy System Analysis course about bottom-up energy optimization. Each identification waits for the discussion to end instead of breaking in the middle._
> > The timeline issue disappears.
> 
> Can you share the original video with us? Let's find this problem.

Here's the video link in OneDrive:
https://1drv.ms/v/s!Ai_5pui2MokRk_IQ2Sjg9EzuCJ6W5Q?e=G3w36g
Hope it helps!

**Comment by Makememo** [comment]
We have made some fix, please see if there is an error timeline. https://memo.ac/releases.html

**Comment by yiqiaowang-arch** [comment]
Unfortunately I still have wrong timelines. This time I used the prompt: "Mathematical Optimization Course. Please add punctuation."
![image](https://github.com/Makememo/MemoAI/assets/28997207/4d544227-ee32-4d6f-94e3-362434f1196b)
I will try again using my previous prompt and see if this time it works.

**Comment by Makememo** [comment]
@yiqiaowang-arch Is there a problem opening VAD?
![image](https://github.com/Makememo/MemoAI/assets/140973261/b063aa79-0f4e-4520-98c8-08aae6d5b489)

**Comment by Makememo** [comment]
And, what is the transfer model?

**Comment by yiqiaowang-arch** [comment]
After the second try, this time the problem remains. 
![image](https://github.com/Makememo/MemoAI/assets/28997207/4dae1fef-6f56-456a-8e2c-0b82a9d5e8a6)

In my case VAD is not enabled.
I am using Medium.en 1.53 GB in all these cases.

**Comment by yiqiaowang-arch** [comment]
[export_log.zip](https://github.com/Makememo/MemoAI/files/13256797/export_log.zip)
After VAD enabled I am not able to see the transcripted text anymore. Here's the log file for you to check.

**Comment by Makememo** [comment]
@yiqiaowang-arch Can you refer to this setting and try again.
![2023-11-04 at 21 57 42@2x](https://github.com/Makememo/MemoAI/assets/140973261/7b6f0273-7e81-4e6c-88bf-5cc8c4a71731)

**Comment by yiqiaowang-arch** [comment]
I have set this value to exactly as shown in your previous screenshot (mode=lenient, threshold=0.3) and it doesn't output anything.

**Comment by Makememo** [comment]
> I have set this value to exactly as shown in your previous screenshot (mode=lenient, threshold=0.3) and it doesn't output anything.

Can you send me log? and try 0.2.
![2023-11-04 at 23 18 50@2x](https://github.com/Makememo/MemoAI/assets/140973261/ee9ff037-589c-438b-82dc-1791025eab08)

**Comment by yiqiaowang-arch** [comment]
Here's the log file with VAD threshold=0.3. I'll try 0.2 now.
[2023-11-05.log](https://github.com/Makememo/MemoAI/files/13260916/2023-11-05.log)

**Comment by Makememo** [comment]
The new version is being tested and will be released recently.  Do you have zoom?  I want to see the problem remotely.

**Comment by yiqiaowang-arch** [comment]
Yes, I am happy to share my experience via zoom. I will be available during the weekends, if that also works for you. I will first try to update to the newest version and see if the problem remains.

**Comment by yiqiaowang-arch** [comment]
Please contact via my email, in case you want me to show how the software behaves.
