### ISSUE TITLE
剪辑：小宇宙播客字幕剪辑出故障

### ISSUE THREAD

**Issue by Wuli-Blizzard** [Makememo/MemoAI#54]
[export_log.zip](https://github.com/Makememo/MemoAI/files/13233969/export_log.zip)

https://github.com/Makememo/MemoAI/assets/81504840/ce2d6bb4-f930-4021-bf54-a16a9d45eeb7

**Comment by Makememo** [comment]
这块还未优化，后续会重写。

**Comment by Wuli-Blizzard** [comment]
> 这块还未优化，后续会重写。

好的，谢谢回答！

**Comment by Makememo** [comment]
已经优化，欢迎体验～
