### ISSUE TITLE
音视频的属性可能是影响转码的主要因素

### ISSUE THREAD

**Issue by Batapha** [Makememo/MemoAI#55]
**Is your feature request related to a problem? Please describe.**
我试了多个视频，发现一些视频即使到了3H的长度，使用medium模型来转码，增加提示词：「输出时候请携带标点符号，如：显质的概念，非自洁蔽的显质。」，用最长的语句长度，能够非常稳定的输出

但是一些音视频即使只有10分钟，结果仍然会存在不增加标点，或是直接无断句的情况

**Describe the solution you'd like**
我猜想是否是音视频的某一个格式或是属性或者是多个属性决定了转码是否能够添加标点

**Describe alternatives you've considered**
可以通过做实验来找到决定的属性，那么就可以将需要转码的音视频通过转码的软件转到这个格式和属性，那么就不需要再关注是否会出现断句的问题

或者是在这个软件中内置这样的转码功能

这样能够提高软件的可用性

**Additional context**

**Comment by Makememo** [comment]
能否发一下 10 分钟的视频，我们排查一下。

**Comment by Makememo** [comment]
这里有提到提示词使用：https://sspai.com/post/83644
