### ISSUE TITLE
提示詞不會用廣東話

### ISSUE THREAD

**Issue by sdugoten** [Makememo/MemoAI#59]
**Describe the bug**
用whisper 的話, 其實可以直接要求whisper 輸出廣東話.  只要video 內的對話是廣東話, 只要在提示詞輸入"以下係香港嘅港式廣東話", 整個transcript 都會直接用廣東話輸出 .  Memo 現時無法做到.

**To Reproduce**
1. 提示詞輸入"以下係香港嘅港式廣東話",

**Expected behavior**
我會expect 會像whisper 直接transcribe 成廣東話
![20231104_123307](https://github.com/Makememo/MemoAI/assets/7108552/c5348c62-bb07-4fd1-8854-3a41faeed2a6)

**Screenshots**
而Memo 用在同一條video 上, 會變成正體中文, 而不是廣東話.  就算提示詞輸入"以下係香港嘅港式廣東話"也沒差.
 
![20231104_124021](https://github.com/Makememo/MemoAI/assets/7108552/a4e525a9-d423-42d1-b650-72831a3bce56)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version: Memo v1.0.11

**Comment by Makememo** [comment]
![2023-11-04 at 22 22 03@2x](https://github.com/Makememo/MemoAI/assets/140973261/e51d6a20-a586-4f88-94a9-da59ab0f8163)
提示词：系香港慨港式廣東話。

**Comment by sdugoten** [comment]
我用你同一條片段, auto 模式，提示词：系香港慨港式廣東話, 結果是顯視中文

![20231104_144047](https://github.com/Makememo/MemoAI/assets/7108552/cca249ed-cb82-4173-9fd7-2f00a1299d39)

![20231104_144139](https://github.com/Makememo/MemoAI/assets/7108552/b01eaa00-86f8-4200-9a2b-edf20ca2a472)

**Comment by sdugoten** [comment]
> ![2023-11-04 at 22 22 03@2x](https://user-images.githubusercontent.com/140973261/280472616-e51d6a20-a586-4f88-94a9-da59ab0f8163.png) auto 模式，提示词：系香港慨港式廣東話。

看這個片就明白.

https://file.io/Lgpda4Dm6Ifl

我用跟你同一個video 做測試, 結果跟你不一樣, 不是transcribe 做廣東話

**Comment by Makememo** [comment]
测试 Large 确实会如此，medium 没问题，怀疑是 ggml 模型转换问题，后续有时间深入看看转换算法。

**Comment by sdugoten** [comment]
> 测试 Large 确实会如此，medium 没问题，怀疑是 ggml 模型转换问题，后续有时间深入看看转换算法。

好, 麻煩了, 請將topic 由closed 變回open.  謝

**Comment by sdugoten** [comment]
另外, 確實是ggml 轉換有問題, 我在別的ggml model 看過有類似情況, 就是transcribe 出來的字句超長, 好像下面我用medium 做出來的字幕

![20231104_171647](https://github.com/Makememo/MemoAI/assets/7108552/20fe1edd-c434-4218-aaff-19949ce52363)
