### ISSUE TITLE
视频的字幕与视频里人物说话的时间点没有匹配上

### ISSUE THREAD

**Issue by Baniel** [Makememo/MemoAI#60]
首先还是要感谢开发者开发一款这么好用的软件。赞。

### **我从YouTube上下载的AI生成式字幕放在MemoAI工具里，会出现视频里的字幕会有延迟的现象。**

问题是这样的：
第一条字幕和视频里的语音都能对的上，但下一秒就出现了字幕延迟的效果。

第一条字幕 对上 第二条语音
第二条字幕 对上 第三条语音
第三条字幕 对上 第四条语音
.....

**Comment by Baniel** [comment]
![Screen Shot 2023-11-05 at 5 55 13 pm](https://github.com/Makememo/MemoAI/assets/7856792/51a01bb4-2a47-4378-bb70-c43bbff75873)

**Comment by Makememo** [comment]
能否发一下原始文件？

**Comment by Baniel** [comment]
由于Github不支持上传我发的“原始文件”的类型，我把原始文件放到了云盘上。辛苦了。
We don’t support that file type.

Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP.


云盘地址：https://pan.baidu.com/s/1qBm_a0aGIbyrRtMMLpnXeQ
密码：jequ

**Comment by Baniel** [comment]
> 由于Github不支持上传我发的“原始文件”的类型，我把原始文件放到了云盘上。辛苦了。 We don’t support that file type.
> 
> Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP.
> 
> 云盘地址：https://pan.baidu.com/s/1qBm_a0aGIbyrRtMMLpnXeQ 密码：jequ

**Comment by 1PercentSync** [comment]
我也遇到这样的情况

**Comment by Makememo** [comment]
应该是用了蒸馏模型，我们即将下掉该模型。

**Comment by Makememo** [comment]
请使用非蒸馏模型，英文推荐 Medium.en
