### ISSUE TITLE
无法创建工作空间

### ISSUE THREAD

**Issue by juzi0551** [Makememo/MemoAI#61]
**Describe the bug**
三项都输入了，但是点击create无反应。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos 13.6.1
 -  - Browser [e.g. chrome, safari]

**Additional context**

**Comment by juzi0551** [comment]
空间路径在download下

**Comment by juzi0551** [comment]
关掉重启就好了

**Comment by Makememo** [comment]
感谢，我们后续观察一下类似 case。
