### ISSUE TITLE
Distil-medium.en very slow, with problematic transcript output

### ISSUE THREAD

**Issue by yiqiaowang-arch** [Makememo/MemoAI#64]
**Describe the bug**
1. the real speed of distil-medium.en on my computer is much slower than Medium.en, which according to model description should be much faster and much more accurate.
2. After 2-3 min of loading, it finally started, but only had transcription of 3 sentences and stopped afterwards. All normal subtitles are corresponding to the first minute of the video.
3. Right after stopping the transcript, a super long subtitle jumped out with only modals, locating at the 11th minute of the video. I suspect that the model was focusing on modals throughout the video, and it lost the capability of separating the sentences, even when I have set certain prompts. (See the first screenshot)

**To Reproduce**
1. Update to the latest version of Memo (v1.0.12).
2. Download Distil-large, Distil-medium.
3. video of slides with clear English sound, with length of 1hr 43min.
5. VAD is turned off. 
6. GPU enabled.
7. prompt: _This is a lecture in Energy System Analysis course. Each identification waits for the discussion to end instead of breaking in the middle._
8. start the transcript and bug appeared.
9. I tried with a new prompt: _This is a lecture in Energy System Analysis course. Each identification waits for the discussion to end instead of breaking in the middle. **Exclude all modals**._ But the bug remained. After 10 minutes of running, the transcript stopped and generate only modals again.

**Screenshot of the bug:**
Result with prompt: _This is a lecture in Energy System Analysis course. Each identification waits for the discussion to end instead of breaking in the middle._
![image](https://github.com/Makememo/MemoAI/assets/28997207/55950a05-bfc6-4461-9787-cb0084b11919)
Result with prompt: _This is a lecture in Energy System Analysis course. Each identification waits for the discussion to end instead of breaking in the middle. **Exclude all modals**._ 
![image](https://github.com/Makememo/MemoAI/assets/28997207/7c22bd41-1cfe-42c1-b574-74873f6769e9)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Memo v1.0.12
 - GPU nVIDIA RTX 3060 Laptop 6GB

**Logs**
[export_log.zip](https://github.com/Makememo/MemoAI/files/13313716/export_log.zip)

**Comment by yiqiaowang-arch** [comment]
With VAD enabled I can generate more things, but mostly they are still modals.
![image](https://github.com/Makememo/MemoAI/assets/28997207/116dd88b-d723-4585-b5d4-40ea6ba5d420)

**Comment by Makememo** [comment]
Thank you for the feedback, we will check it.

**Comment by Makememo** [comment]
After our testing, the model adaptation of Distil-medium.en is not very good, and we have the opportunity to optimize it later.

**Comment by Makememo** [comment]
We have removed this model, and medium.en is recommended.
