### ISSUE TITLE
生成视频的GUI界面出现问题

### ISSUE THREAD

**Issue by Baniel** [Makememo/MemoAI#65]
还是感谢软件的开发者，辛苦了。

由于视频时长太长（50分钟左右），生成视频的UI导致把生成视屏的按钮，挤到了屏幕的最右边，以至于无法点击到button.
<img width="601" alt="Screen Shot 2023-11-12 at 12 18 51 pm" src="https://github.com/Makememo/MemoAI/assets/7856792/9bfab127-32e3-49d2-8984-79d2b645907f">

<img width="1216" alt="Screen Shot 2023-11-12 at 12 19 00 pm" src="https://github.com/Makememo/MemoAI/assets/7856792/a3fb4f89-90c7-4f38-8f87-b2bb8cf3f9a6">

**Comment by Makememo** [comment]
新版本已经解决
