### ISSUE TITLE
預先設置替換字詞功能

### ISSUE THREAD

**Issue by Soren90912** [Makememo/MemoAI#66]
**可以增加預先設置替換字詞的功能嗎**
大概是這樣子的概念， 設置完之後未來碰到相同的字就會自動替換
<img width="500" alt="SCR-20230730-ngwb" src="https://github.com/Makememo/MemoAI/assets/150583673/90358d33-7316-40f5-811c-8e0fa0a15401">

**Comment by Makememo** [comment]
计划中了

**Comment by Makememo** [comment]
已经更新：https://memo.ac/releases

**Comment by Soren90912** [comment]
找不到預先設置替換的選項

**Comment by Makememo** [comment]
![2023-11-24 at 10 28 39@2x](https://github.com/Makememo/MemoAI/assets/140973261/587d728c-4e46-420d-89ac-3a7a5d7423b9)
