### ISSUE TITLE
谷歌翻译，报网络问题

### ISSUE THREAD

**Issue by nineSean** [Makememo/MemoAI#7]
代理测试 ok，自己使用也正常，但是

<img width="653" alt="image" src="https://github.com/Makememo/MemoAI/assets/21988006/99377b92-e61b-4408-b9de-ee140dc1466d">
<img width="849" alt="image" src="https://github.com/Makememo/MemoAI/assets/21988006/a4c38d05-bb3d-49bb-a2f5-b52dd290d19f">

**Comment by Makememo** [comment]
可以提供一下 log 文件哈～
