### ISSUE TITLE
无法建立工作区

### ISSUE THREAD

**Issue by rockets-cn** [Makememo/MemoAI#70]
**Describe the bug**
无法建立工作区

**To Reproduce**
1. 选择本地媒体
2. 输入工作空间名称、文件夹、描述
3. 点击创建
5. 没有反应

**Expected behavior**
应可以选择相应目录下文件

**Screenshots**
![image](https://github.com/Makememo/MemoAI/assets/2182466/40a55687-fb4e-4ee1-8848-e8187dd912b4)

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 版本 14.0
 - Version v1.0.13

**Additional context**
None

**Comment by AllenRay456** [comment]
i meet same bug,  just reopen app , it solved

**Comment by Makememo** [comment]
麻烦设置 - 实验室导出一下日志。

**Comment by Makememo** [comment]
已经定位问题，下个 版本解决。

**Comment by Makememo** [comment]
已经更新：https://memo.ac/releases
