### ISSUE TITLE
无法上传本地视频

### ISSUE THREAD

**Issue by hx3333** [Makememo/MemoAI#74]
**Describe the bug**
打开软件无法上传本地视频mp4格式，软件没有任何响应和提示

**To Reproduce**
查看日志，报错Error: ffmpeg exited with code 1: No decoder for stream #0:0, filtering impossible
Error configuring complex filters.

**Expected behavior**
希望前端能弹出报错提示

**Screenshots**
![image](https://github.com/Makememo/MemoAI/assets/44716826/d9a4fd1a-e2fb-413b-87ce-e40a90e8a7e8)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version ：119.0

**Additional context**

**Comment by Makememo** [comment]
你好，请问可以发一下原始视频么？使用链接或者 ZIP 包。

**Comment by hx3333** [comment]
> 你好，请问可以发一下原始视频么？使用链接或者 ZIP 包。

https://youtu.be/u1U589o_f_I?si=O8WjkW045APUHAZE
感谢这么晚还回bug

**Comment by Makememo** [comment]
测试复现了，我们修复一下。

**Comment by Makememo** [comment]
我们测试新版已经可以正常使用了。https://memo.ac/download
