### ISSUE TITLE
Hope to be able to identify batch links

### ISSUE THREAD

**Issue by DavidJoyDong** [Makememo/MemoAI#76]
目前的批量依然需要手动把链接一个一个地粘贴进来并按「新增」，没有达到批量复制批量识别的程度。

希望可以识别一行一个 url 的批量链接。

![image](https://github.com/Makememo/MemoAI/assets/47232992/879262f5-86db-40eb-90b8-13d2bafa5711)

相似需求参考：
希望增加批量下载不同视频的功能 - 唧唧交流 - 唧唧 - jijidown
https://forum.hentai.sh/t/topic/765

**Comment by Makememo** [comment]
已经更新，注意没有做链接匹配。https://memo.ac/zh/releases
