### ISSUE TITLE
Notion Export Not Functional

### ISSUE THREAD

**Issue by canzj** [Makememo/MemoAI#77]
**Describe the bug**
'Export to Notion' function not working. I have already set up Notion secret and page id and connected to the Internet.

**To Reproduce**
1. Go to the transcripted video
2. Click on '导出'
3. 'Exporting To Notion' is not working.

**Expected behavior**
Export transcript to notion normally.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 1.0.13

**Comment by Makememo** [comment]
It could be one of two things:
1. No integration into Notion Connections is added
2. Too many subtitles, Notion limit.

**Comment by Makememo** [comment]
https://github.com/Makememo/MemoAI/releases/tag/v1.3.1
