### ISSUE TITLE
无法使用非api.开头的api服务器

### ISSUE THREAD

**Issue by 1PercentSync** [Makememo/MemoAI#78]
**Describe the bug**
无法使用非api开头域名的服务器

**To Reproduce**
https://api.openai-proxy.org 可用
https://oneapi.1percentsync.games 报错
https://api.****.monster 可用/应提供商要求隐藏
**Expected behavior**
在其他软件可用的api服务器都可用

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser N/A
 - Version 1.0.13

**Additional context**
[export_log.zip](https://github.com/Makememo/MemoAI/files/13405852/export_log.zip)

**Comment by Makememo** [comment]
We are going to drop this way, there is a security risk.🤔

**Comment by Makememo** [comment]
这个能力后续不准备支持， 我们观察下来只有个位数人在使用，同时因为三方接口和 Open AI 不一致，增加我们客服支持成本。
