### ISSUE TITLE
导出双语字幕异常

### ISSUE THREAD

**Issue by nineSean** [Makememo/MemoAI#8]
导出 lrc 格式双语字幕，预览是包含双语，实际导出的只有原始语言

<img width="1137" alt="image" src="https://github.com/Makememo/MemoAI/assets/21988006/3800d56f-bdea-4abc-bf6c-e0d6fb36cf2f">

**Comment by Makememo** [comment]
已知问题，后续会优化双语效果。

**Comment by Makememo** [comment]
已经支持
