### ISSUE TITLE
付费购买后无法收到邮件，qq邮箱。

### ISSUE THREAD

**Issue by 854939687** [Makememo/MemoAI#80]
如题，付费购买后无法收到邮件，qq邮箱。

**Comment by Makememo** [comment]
可以检查一下垃圾邮箱以及收信是否被拦截。

https://app.lemonsqueezy.com/my-orders 这里也可以查询过往购买记录。

**Comment by 854939687** [comment]
垃圾邮箱和拦截都没有，也确定邮箱没有输错。用免费版测试了163邮箱，一切正常。唯独qq邮箱不行。收不到邮件，没办法进入你发的地址。

**Comment by Makememo** [comment]
我用邮箱直接发送给你一份邮件。

https://kf.qq.com/faq/1612272uiQRf161227mYZZFF.html

一般是这里查看拦截

**Comment by Makememo** [comment]
没办法进入我发的地址，这里需要开代理看看。
