### ISSUE TITLE
无法再直接下载Large v2模型

### ISSUE THREAD

**Issue by 1PercentSync** [Makememo/MemoAI#81]
**Describe the bug**
https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large.bin
此链接已经无法再下载v2模型，原因可能是是更新了v3之后v2被命名为ggml-large-v2.bin，v3被命名为ggml-large.bin，然后更新了统一命名为了ggml-large-v3.bin

**To Reproduce**
再软件中点击Large v2 whisper模型的下载

**Expected behavior**
正常下载对应版本的模型

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser N/A
 - Version 1.0.13

**Additional context**
手动下载ggml-large-v3.bin放进模型文件夹并重命名为ggml-large.bin重启软件可以暂时解决

**Comment by Makememo** [comment]
下个版本修复

**Comment by Makememo** [comment]
已经更新：https://memo.ac/releases
