### ISSUE TITLE
win11版本，创建工作空间的步骤卡住了

### ISSUE THREAD

**Issue by hidoos** [Makememo/MemoAI#83]
**Describe the bug**
安装完成之后，创建 workspace 的过程就卡住了
**To Reproduce**

![Memo_u5agqm0mmt](https://github.com/Makememo/MemoAI/assets/1256985/8f923404-b858-4c8a-b78f-57b04a79f28d)

**Expected behavior**
能够创建工作空间。

**Screenshots**

**Desktop (please complete the following information):**
 - OS: win11
 - Browser chrome
 - Version 1.0.13

**Additional context**

**Comment by Makememo** [comment]
重启一下再试试

**Comment by hidoos** [comment]
重启之后确实就可以了

**Comment by zfdang** [comment]
遇到同样的问题，重启之后解决...

这个体验太糟糕了, 让人以为这个软件完全不可用啊
