### ISSUE TITLE
transcript 没有内容输出

### ISSUE THREAD

**Issue by gstar175** [Makememo/MemoAI#84]
**Describe the bug**
transcript 没有内容输出

**To Reproduce**

[2023-11-21.log](https://github.com/Makememo/MemoAI/files/13424386/2023-11-21.log)

1. 在 Setting 设定好 OpenAI，下载模型 (small)
2. 建立工作区
3. 复制 youtube 链接贴上，点击 Start
4. 选择模型 small，点击 Start
5. 开始 transcript
6. 没有内容输出

**Expected behavior**
显示字幕

**Screenshots**
<img width="990" alt="01" src="https://github.com/Makememo/MemoAI/assets/324946/0f0575bb-dbae-4624-9b0f-d150c9c6d14f">
<img width="989" alt="02" src="https://github.com/Makememo/MemoAI/assets/324946/73731273-7a86-4e32-9023-71e3b726ce9f">
<img width="990" alt="03" src="https://github.com/Makememo/MemoAI/assets/324946/bfdaaf5b-0c43-495f-a6bb-c144a9c84962">

**Desktop (please complete the following information):**
 - OS: macOS 13.4.1 (c)（22F770820d）
 - Browser: Arc
 - Version: Apple Intel 1.0.13

**Comment by gstar175** [comment]
选择 CPU，advanced setting 的部分没有变动过。

**Comment by gstar175** [comment]
重启之后正常了... 哈哈  ^_^;

**Comment by Makememo** [comment]
OK，有的时候模型也有问题，后续我们观察一下。
