### ISSUE TITLE
对于转录识别幻觉的建议

### ISSUE THREAD

**Issue by songquanxu** [Makememo/MemoAI#85]
**Is your feature request related to a problem? Please describe.**
目前虽然有人声分离，但是仍旧会出现莫名其妙的识别幻觉，大量的重复内容，但是回听对应内容和之前的差异不大，猜测也许是系统识别过程中临时的资源不足导致的。

**Describe the solution you'd like**
建议可以在识别后（自动）批量找出大量重复的内容，提供仅对这些内容重新识别的功能。

完整的重新识别一方面消耗时间，另一方面对于内容的完整性没有确定的促进效果。

**Describe alternatives you've considered**
当然，如果自动找出重复内容有困难的话，建议可以提供人工对识别结果多选的方式，对相应片段做二次识别

**Additional context**

**Comment by Makememo** [comment]
中文模式会多一些，我们有中文模型提供给 Pro，会有效降低幻觉。

**Comment by Makememo** [comment]
AI 模型幻听的来源是什么？

经过我们排查，AI 幻听很大来源是系统性能不够导致，如果你是 4090 显卡 + large + 32G 内存模型，基本不会出问题。

如果你的性能不达标，建议退回到 Medium 或者更换其他模型。

接下来就是空白、背景音导致的幻听，这里启用人声检测即可，如果还出现，调大数值。

接下来就是提示词的控制，可以将一直重复片段里面的内容输入到提示词，尝试引导 AI 识别。
