### ISSUE TITLE
无法设立文件夹 点击创建 没有反应

### ISSUE THREAD

**Issue by yang44yang** [Makememo/MemoAI#86]
![无法创立个人空间](https://github.com/Makememo/MemoAI/assets/37780510/f00ad6f7-f333-47b7-a657-f5e64225cbc5)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Makememo** [comment]
重启即可，下个版本修复。

**Comment by Makememo** [comment]
已经更新：https://memo.ac/releases
