### ISSUE TITLE
Unable to get youtube link media information

### ISSUE THREAD

**Issue by yang44yang** [Makememo/MemoAI#89]
![WX20231123-095651@2x](https://github.com/Makememo/MemoAI/assets/37780510/8310c8f0-4595-4767-b477-f02304c85112)
![WX20231123-103240@2x](https://github.com/Makememo/MemoAI/assets/37780510/423fedde-eed5-4e0f-a681-126132a9d36f)
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Makememo** [comment]
Settings-Lab, Export Log

**Comment by Makememo** [comment]
重新下载即可
