### ISSUE TITLE
语言转文字时一直重复某句话

### ISSUE THREAD

**Issue by MartialBE** [Makememo/MemoAI#9]
我在使用mp4或者mp3转文字时，会出现一直重复输出某句话的字幕，这期间是有说其他的，但是都被忽略了。过段时间又恢复正常了。
尝试了换了几个视频，以及更换模型都是一样的情况。

设备：Mac mini M1, 2020
系统：MacOS 14 Bate 6
软件版本： v1.0.4
使用模型：Medium 以及 Medium.en

[![i-Shot-2023-08-25-22-03-27.png](https://i.postimg.cc/d3k59D9Q/i-Shot-2023-08-25-22-03-27.png)](https://postimg.cc/JH83rrgS)

**Comment by MartialBE** [comment]
又尝试了 Tiny、Tiny.en、Base、Base.en、Small、Small.en 这6个。
可能和我配置有关系？ 我的电脑是8G乞丐版的。
Tiny、Tiny.en、Base 这三个模型能正常识别，没有问题。
Tiny、Tiny.en 是其中识别最好的.... 断句啥的都没问题。
Base 断句有点问题....

Base.en、Small、Small.en 这三个模型完全不行，识别出来的全是错的。
以上所有测试都是同一段音频，指定了语言，其他设置默认。

[![i-Shot-2023-08-25-22-29-49.png](https://i.postimg.cc/s2kV9HSt/i-Shot-2023-08-25-22-29-49.png)](https://postimg.cc/CZ4TwNcN)

[![i-Shot-2023-08-25-22-30-44.png](https://i.postimg.cc/85LTydms/i-Shot-2023-08-25-22-30-44.png)](https://postimg.cc/ZBKkndgh)

[![i-Shot-2023-08-25-22-31-46.png](https://i.postimg.cc/jSjds7tk/i-Shot-2023-08-25-22-31-46.png)](https://postimg.cc/bsKjgdGQ)

**Comment by Makememo** [comment]
抱歉带来不好的体验，问题已经定位，下个版本修复。
