### ISSUE TITLE
Support for subtitle synthesis video

### ISSUE THREAD

**Issue by zfdang** [Makememo/MemoAI#90]
1. 导出带字幕的视频，程序提示结束了，但是实际上后台并没有结束，还在生成视频。这时候如果你尝试去打开视频，就会提示文件损坏...
试了两次，才发现实际上是没导出完呢
2. 导出的视频里，字幕会重叠，会超出屏幕的宽度... 基本属于不可用状态

macos/m1

**Comment by Makememo** [comment]
已经解决
