### ISSUE TITLE
出现了request to https://license.memo.ac/v1/licenses/activatefailed,reason:read ECONNRESET的报错

### ISSUE THREAD

**Issue by Diplproveably** [Makememo/MemoAI#91]
![image](https://github.com/Makememo/MemoAI/assets/111405888/799ff06e-bceb-4a5a-b3a0-4f2388ddb949)

**Comment by Makememo** [comment]
这个网址你能直接访问么？不能的话，开启 or 关闭代理。

**Comment by Diplproveably** [comment]
> 这个网址你能直接访问么？不能的话，开启 or 关闭代理。

关闭代理也还是会出现报错，访问`https://license.memo.ac/v1/licenses/activatefailed`这个网址的话不管开启代理还是关闭代理出现的都是`Unexpected token '<', "<!DOCTYPE "... is not valid JSON`


又试着在飞书网盘里头下载1.0.12然后安装，这样没有任何问题。但是用github发布的1.1.0就会出现这个报错，可能确实是1.1.0这个版本的问题。

**Comment by Makememo** [comment]
有点奇怪，走这里吧，麻烦激活后发我一下日志。

下载链接：https://memo.ac/releases.html

邀请码：
AqCL-7Btr-KZpN-zsnq
Et9x-rnR2-8cWW-8bv4
Lro4-JZS3-5Yu6-tVUw
DrHa-gL6s-dGyJ-3HXf
XYo2-65tF-bJ3L-54Ao

**Comment by Diplproveably** [comment]
> 有点奇怪，走这里吧，麻烦激活后发我一下日志。
> 
> 下载链接：https://memo.ac/releases.html
> 
> 邀请码： AqCL-7Btr-KZpN-zsnq Et9x-rnR2-8cWW-8bv4 Lro4-JZS3-5Yu6-tVUw DrHa-gL6s-dGyJ-3HXf XYo2-65tF-bJ3L-54Ao

正常了，V3模型也可以使用。不过我没有在memo中找到日志，在电脑里头搜索了一下找到了几个名字是log的文件，是这几个吗？
![image](https://github.com/Makememo/MemoAI/assets/111405888/73cba1c3-2348-4de3-adb3-1448716eac65)

**Comment by Makememo** [comment]
设置 -- 实验室可以导出

**Comment by Diplproveably** [comment]
> 设置 -- 实验室可以导出

昨天找到这个按钮了，不过点了之后没有任何反应也没有找到任何可以进行下一步操作的地方，所以就以为我找错了😂
![image](https://github.com/Makememo/MemoAI/assets/111405888/f6caa95d-4925-4aa7-b5af-20fbf02747ab)

要不你给我说一下那个文件是日志文件，我直接打包发给你吧 ヾ(￣▽￣)~~

**Comment by longhaiqwe** [comment]
内测激活的过程中也出现了这个错误提示，原因应该是在激活的过程中就受到了公司网络的阻断，能否在激活前就有一个设置代理的入口？（类似飞书，在登录前就能够设置代理，如下图）
![image](https://github.com/Makememo/MemoAI/assets/6258657/db673214-e10e-46cc-979f-57d2a1a37635)

**Comment by MoonTracer732** [comment]
确实我也遇到了相同的代理问题，现使用了最后一个激活码激活

**Comment by MoonTracer732** [comment]
[export_log.zip](https://github.com/Makememo/MemoAI/files/15151829/export_log.zip)
