### ISSUE TITLE
Requires CoreML version of Mac M-series CPU

### ISSUE THREAD

**Issue by ranrancc** [Makememo/MemoAI#93]
感谢开发者的努力尝试
我是一位大学教师，平时喜欢轻巧的笔记本，在用Macbook Air M1 16+1T的笔记本，
在混合式教学中，将微课听写字幕后，再让AI帮我总结微课内容并生成所有知识点及对应原文解释的列表，以及该知识点在视频中出现的时间，能够大大方便学生的学习。

在1.0.07版里加入了 Core ML 版本的支持后，转写速度突然快了3倍，同时CPU占用也不高，耗电也没有增加，对于我这种显卡也弱的笔记本来说确实很好使用。

好像是在1.0.09还是哪个版本，取消了这个特性的支持。比较起来，用GPU加速版可能在高端显卡的机器上提速会更明显一些。而对于我用的这台笔记本，CoreML是它速度最快耗电最小的方式。

能否在之后的版本中保留这个特性，或者给我能够支持它的最后的版本的下载链接，我以后用老版本不更新也行。
谢谢。

**Comment by Makememo** [comment]
OK，我们后续迭代集成上。

**Comment by ranrancc** [comment]
谢谢，开发者辛苦了

**Comment by Makememo** [comment]
实验室开启：https://memo.ac/zh/releases，且需要额外下载 encoder.mlmodelc https://huggingface.co/ggerganov/whisper.cpp/tree/main
