### ISSUE TITLE
Unable to export video card on screenshot page

### ISSUE THREAD

**Issue by yang44yang** [Makememo/MemoAI#94]
/*
![无法导出页面](https://github.com/Makememo/MemoAI/assets/37780510/018e6c5b-66c0-47b5-bf09-3174022a6217)
*Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Makememo** [comment]
还在开发中。

**Comment by Makememo** [comment]
已经支持
