### ISSUE TITLE
openai翻译，不转行

### ISSUE THREAD

**Issue by amofillin-123** [Makememo/MemoAI#95]
M1 PRO mbp，系统版本13.6.2
memo版本：V1.1.1
![CleanShot 2023-11-29 at 09 00 05@2x](https://github.com/Makememo/MemoAI/assets/76163765/b4f75fd9-20d9-434d-b11a-ceccdcc188ed)

**Comment by Makememo** [comment]
https://memo.ac/zh/blog/How-to-use-AI-to-translate-subtitles 如何使用 Memo 进行 AI 字幕翻译

请参考上文学习使用 AI 翻译。
