### ISSUE TITLE
翻译新增Azure openai service

### ISSUE THREAD

**Issue by clark-cui** [Makememo/MemoAI#97]
因为openai很容易封号，所以现在用azure openai service的人应该挺多的。
这个实现应该也不是很困难，辛苦考虑新增一下？

**Comment by Makememo** [comment]
Let's think about it later. at present, there is only one example of your feedback.

**Comment by photon-phalanx** [comment]
Hello,
I am also a user of the Azure OpenAI service. As you may understand, using it in China tends to be much more stable. I am hoping that you could consider adding support for it. Thanks.

**Comment by Makememo** [comment]
Already supported, go to Settings - Integration - Refresh button in the upper right corner.
